const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const catalog=require('../../product/catalog.json');
const passes=Object.fromEntries(catalog.passes.map(p=>[p.id,p.credits]));
const costs=Object.fromEntries(catalog.models.map(m=>[m.model,m.credits]));
const available=new Set(catalog.models.filter(m=>m.available).map(m=>m.model));
const fail=(message,status=409)=>{throw Object.assign(Error(message),{status})};
class Ledger{
 constructor(file,{clock=Date.now,freeMonthly=Number(process.env.FREE_MONTHLY_MEMORY_CREDITS??15)}={}){if(!Number.isSafeInteger(freeMonthly)||freeMonthly<0)throw Error('INVALID_FREE_ALLOWANCE');this.file=file;this.clock=clock;this.freeMonthly=freeMonthly;this.data=this.load()}
 load(){try{return{accounts:{},identities:{},verifiedPurchases:{},deductions:{},installations:{},searches:{},...JSON.parse(fs.readFileSync(this.file,'utf8'))}}catch(e){if(e.code!=='ENOENT')throw e;return{accounts:{},identities:{},verifiedPurchases:{},deductions:{},installations:{},searches:{}}}}
 save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const temp=`${this.file}.${process.pid}.tmp`;fs.writeFileSync(temp,JSON.stringify(this.data,null,2),{mode:0o600});fs.renameSync(temp,this.file)}
 cycle(){const d=new Date(this.clock());return{key:d.toISOString().slice(0,7),end:new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)).toISOString()}}
 account(id){if(!id)fail('ACCOUNT_REQUIRED',401);const a=this.data.accounts[id]??={balance:0,subscription:{status:'NONE'},transactions:[],purchases:[]};a.freeGrants??={};return a}
 resolveIdentity(provider,subject){if(!provider||!subject)fail('IDENTITY_REQUIRED',401);const key=`${provider}:${subject}`;if(this.data.identities[key])return this.data.identities[key];const id=crypto.randomUUID();this.data.identities[key]=id;this.account(id);this.save();return id}
 register(id,installation){if(typeof installation!=='string'||! /^[a-zA-Z0-9_-]{16,128}$/.test(installation))fail('INVALID_INSTALLATION',400);const key=crypto.createHash('sha256').update(installation).digest('hex');this.data.installations[key]??={cycles:{},attestation:'UNATTESTED'};this.account(id).installation=key;this.pool(id);this.save()}
 pool(id){const a=this.account(id),cycle=this.cycle();if(!a.installation)return null;const installation=this.data.installations[a.installation];let p=installation.cycles[cycle.key];if(!p){p=installation.cycles[cycle.key]={remaining:0,owner:null};}if(!p.owner&&!a.freeGrants[cycle.key]){p.owner=id;p.remaining=this.freeMonthly;a.freeGrants[cycle.key]=a.installation;a.transactions.push(this.tx(Object.keys(a.freeGrants).length>1?'FREE_MONTHLY_RESET':'FREE_MONTHLY_GRANT',this.freeMonthly,a.balance,'Monthly free credits',{freeCredits:this.freeMonthly}));this.save()}return p.owner===id?p:null}
 view(id){const a=this.account(id),p=this.pool(id),c=this.cycle();const transactions=[...a.transactions].reverse();const searches=a.transactions.filter(t=>t.type==='DEBIT');const month=searches.filter(t=>t.createdAt.startsWith(c.key));return{accountId:id,balance:a.balance,freeMonthlyRemaining:p?.remaining??0,freeMonthlyTotal:this.freeMonthly,nextResetAt:c.end,totalAvailable:a.balance+(p?.remaining??0),creditsExpire:false,subscription:a.subscription,studio_ai_allowance_total:a.studio_ai_allowance_total??null,studio_ai_allowance_remaining:a.studio_ai_allowance_remaining??null,studio_ai_cycle_start:a.studio_ai_cycle_start??null,studio_ai_cycle_end:a.studio_ai_cycle_end??null,transactions,usage:{month:{freeCreditsUsed:month.reduce((n,t)=>n+(t.freeSpent||0),0),purchasedCreditsUsed:month.reduce((n,t)=>n+(t.purchasedSpent??-t.credits),0),searchCount:month.length},byModel:Object.fromEntries(catalog.models.map(m=>[m.model,month.filter(t=>t.model===m.model).length])),allTime:{searchesCompleted:searches.length,purchasedCreditsUsed:searches.reduce((n,t)=>n+(t.purchasedSpent??-t.credits),0),passesPurchased:a.purchases.length}}}}
 purchase(id,passId,receipt){const credits=Object.hasOwn(passes,passId)?passes[passId]:undefined;if(!credits)fail('UNKNOWN_PASS',400);if(typeof receipt!=='string'||!receipt||receipt.length>200)fail('INVALID_RECEIPT',400);const owner=this.data.verifiedPurchases[receipt];if(owner&&owner!==id)fail('PURCHASE_OWNED_BY_ANOTHER_ACCOUNT');if(owner)return this.view(id);const a=this.account(id);a.balance+=credits;a.purchases.push({passId,storeTransactionId:receipt,credits});a.transactions.push(this.tx('MEMORY_PASS_GRANT',credits,a.balance,'Memory Pass',{id:receipt,passId,purchasedSpent:0}));this.data.verifiedPurchases[receipt]=id;this.save();return this.view(id)}
 deduct(id,model,requestId){if(!available.has(model))fail('MODEL_UNAVAILABLE');if(typeof requestId!=='string'||!requestId||requestId.length>200)fail('REQUEST_ID_REQUIRED',400);const owner=this.data.deductions[requestId];if(owner&&owner!==id)fail('REQUEST_ID_OWNED_BY_ANOTHER_ACCOUNT');if(owner)return this.view(id);const cost=costs[model],a=this.account(id),p=this.pool(id);if(a.balance+(p?.remaining||0)<cost)fail('INSUFFICIENT_CREDITS',402);const freeSpent=Math.min(cost,p?.remaining||0),purchasedSpent=cost-freeSpent;if(p)p.remaining-=freeSpent;a.balance-=purchasedSpent;a.transactions.push(this.tx('DEBIT',-cost,a.balance,`${catalog.models.find(m=>m.model===model).name} search`,{id:requestId,model,freeSpent,purchasedSpent}));this.data.deductions[requestId]=id;this.save();return this.view(id)}
 startSearch(id,model,requestId){if(!available.has(model))fail('MODEL_UNAVAILABLE');if(typeof requestId!=='string'||!requestId||requestId.length>200)fail('REQUEST_ID_REQUIRED',400);const old=this.data.searches[requestId];if(old){if(old.accountId!==id||old.model!==model)fail('SEARCH_ID_CONFLICT');return old}if(this.view(id).totalAvailable<costs[model])fail('INSUFFICIENT_CREDITS',402);const job={accountId:id,model,state:'PENDING'};this.data.searches[requestId]=job;this.save();return job}
 finishSearch(id,requestId,outcome){const job=this.data.searches[requestId];if(!job||job.accountId!==id)fail('SEARCH_NOT_FOUND',404);if(!['SUCCESS','FAILED','CANCELLED'].includes(outcome))fail('INVALID_OUTCOME',400);if(job.state!=='PENDING')return this.view(id);if(outcome==='SUCCESS')this.deduct(id,job.model,requestId);job.state=outcome;this.save();return this.view(id)}
 studio(id,active){if(typeof active!=='boolean')fail('INVALID_ENTITLEMENT',400);const a=this.account(id);if((a.subscription.status==='ACTIVE')===active)return this.view(id);a.subscription={status:active?'ACTIVE':'NONE',tier:catalog.studioEntitlement,test:true};a.transactions.push(this.tx(active?'STUDIO_ENTITLEMENT_START':'STUDIO_ENTITLEMENT_END',0,a.balance,'Studio test entitlement'));this.save();return this.view(id)}
 restore(id){return this.view(id)}
 tx(type,credits,balanceAfter,description,extra={}){return{id:crypto.randomUUID(),type,credits,balanceAfter,description,createdAt:new Date(this.clock()).toISOString(),...extra}}
}
module.exports={Ledger,passes,costs,available,catalog};
