'use strict';
function betaReport(ops,ledger,analytics){
 const now=ops.clock(),day=86400000,state=analytics.snapshot(),testers=ops.data.testers,ids=new Set(testers.map(t=>t.accountId).filter(Boolean));
 const events=state.events.filter(e=>e.environment===ops.environment&&e.metadata.channel===ops.channel&&ids.has(e.accountId)),days=Object.values(state.days).filter(d=>d.environment===ops.environment);
 const jobs=Object.values(ledger.data.searches||{}).filter(j=>ids.has(j.accountId)&&j.channel===ops.channel),feedback=ops.data.feedback,current=ops.current();
 const active=new Set(events.filter(e=>Date.parse(e.at)>=Date.parse(new Date(now).toISOString().slice(0,10))&&['session_started','session_active','search_started','editor_opened'].includes(e.type)).map(e=>e.accountId));
 const mean=xs=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null,rate=(n,d)=>d?Math.round(n/d*1000)/10:null;
 const errors={};for(const e of events.filter(e=>['client_error','error_occurred'].includes(e.type))){const key=[e.metadata.errorCode,e.metadata.platform,e.metadata.appVersion].join('|');const g=errors[key]??={key,code:e.metadata.errorCode,platform:e.metadata.platform,version:e.metadata.appVersion||'UNKNOWN',firstSeen:e.at,lastSeen:e.at,count:0,users:new Set()};g.count++;g.users.add(e.accountId);g.firstSeen=g.firstSeen<e.at?g.firstSeen:e.at;g.lastSeen=g.lastSeen>e.at?g.lastSeen:e.at}
 const groups=Object.values(errors).map(g=>({...g,affectedUsers:g.users.size,users:undefined,repeat:g.count>1}));
 const directory=testers.map(t=>{const own=events.filter(e=>e.accountId===t.accountId);return{...t,feedbackCount:feedback.filter(f=>f.reporter===t.accountId).length,errorCount:own.filter(e=>['client_error','error_occurred'].includes(e.type)).length,searches:jobs.filter(j=>j.accountId===t.accountId).length,crashes:null}});
 const coverage={};for(const t of testers){const c=t.context;if(!c)continue;const key=[c.platform,c.manufacturer,c.modelFamily,c.osVersion,c.ramClass,c.capabilityClass,c.vulkan].join('|');coverage[key]??={...c,testers:0,errors:0,tested:!!t.lastActive,crashRate:null};coverage[key].testers++;coverage[key].errors+=directory.find(d=>d.id===t.id).errorCount}
 const searchFeedback=feedback.filter(f=>f.search),quality=Object.entries(Object.groupBy(searchFeedback,f=>[f.search.model||'UNKNOWN',f.context.appVersion||'UNKNOWN'].join('|'))).map(([key,rows])=>({group:key,correct:rows.filter(f=>f.search.outcome==='CORRECT').length,wrong:rows.filter(f=>f.search.outcome==='WRONG').length,notFound:rows.filter(f=>f.search.outcome==='NOT_FOUND').length,timestampWrong:rows.filter(f=>f.search.outcome==='TIMESTAMP_WRONG').length,tooSlow:rows.filter(f=>f.search.outcome==='TOO_SLOW').length,correctRate:rate(rows.filter(f=>f.search.outcome==='CORRECT').length,rows.filter(f=>['CORRECT','WRONG','NOT_FOUND'].includes(f.search.outcome)).length)}));
 const saves=events.filter(e=>e.type==='edit_saved').length,saveFailures=events.filter(e=>e.metadata.errorCode==='SAVE_FAILED').length;
 const retained=d=>{const eligible=testers.filter(t=>t.acceptedAt&&Date.parse(t.acceptedAt)>=Date.parse(state.startedAt)&&Date.parse(t.acceptedAt)+(d+1)*day<now&&Date.parse(t.acceptedAt)+d*day>now-analytics.rawDays*day);const returned=eligible.filter(t=>events.some(e=>e.accountId===t.accountId&&e.at.slice(0,10)===new Date(Date.parse(t.acceptedAt)+d*day).toISOString().slice(0,10)&&['session_started','session_active','search_started','editor_opened'].includes(e.type)));return{day:d,eligible:eligible.length,returned:returned.length,rate:rate(returned.length,eligible.length)}};
 const installed=testers.filter(t=>t.context?.buildNumber),onCurrent=installed.filter(t=>t.context.buildNumber===current?.buildNumber),previous=ops.data.releases.filter(r=>r.id!==current?.id&&r.status!=='WITHDRAWN').at(-1);
 return{environment:ops.environment,channel:ops.channel,required:ops.required,generatedAt:ops.now(),summary:{invited:testers.length,active:testers.filter(t=>t.status==='ACTIVE').length,activated:testers.filter(t=>t.acceptedAt).length,pending:testers.filter(t=>t.status==='INVITED').length,dau:active.size,feedbackThisWeek:feedback.filter(f=>Date.parse(f.createdAt)>=now-7*day).length,openBugs:feedback.filter(f=>!['VERIFIED','CLOSED'].includes(f.status)).length,criticalBugs:ops.gate().criticalBugs,crashFreeSessions:null,searchesPerTester:ids.size?jobs.length/ids.size:null,successfulSearches:jobs.filter(j=>j.state==='SUCCESS').length,searchLatencyMs:mean(jobs.map(j=>j.durationMs).filter(Number.isFinite)),searchFeedback:searchFeedback.length,memoryPassInterest:null,memoryPassPurchases:events.filter(e=>e.type==='pass_purchased').length,studioInterest:events.filter(e=>e.type==='feature_interest').length},directory,retention:[retained(1),retained(7)],adoption:{current:current?{version:current.version,build:current.buildNumber}:null,knownBuilds:installed.length,unknownBuilds:testers.length-installed.length,currentPercent:rate(onCurrent.length,installed.length),previousPercent:rate(installed.filter(t=>t.context.buildNumber===previous?.buildNumber).length,installed.length),outdated:installed.filter(t=>current&&Number(t.context.buildNumber)<Number(current.buildNumber)).length,history:testers.flatMap(t=>(t.adoption||[]).map(a=>({...a,tester:t.id})))},quality,editor:{opens:events.filter(e=>e.type==='editor_opened').length,saves,saveFailures,saveSuccessRate:rate(saves,saves+saveFailures),undo:events.filter(e=>e.type==='edit_tool_used'&&e.metadata.tool==='undo').length,averageSessionMs:null,crashRate:null},errors:groups,deviceCoverage:Object.values(coverage),cohorts:['LOW_END_DEVICE','VIDEO_TESTERS'].map(cohort=>({cohort,testers:testers.filter(t=>t.cohort===cohort).length,feedback:feedback.filter(f=>testers.some(t=>t.accountId===f.reporter&&t.cohort===cohort)).length,searchLatencyMs:mean(jobs.filter(j=>testers.some(t=>t.accountId===j.accountId&&t.cohort===cohort)).map(j=>j.durationMs).filter(Number.isFinite)),startupMs:null,memoryPressure:null,proxyUsage:null,indexTime:null})),gate:ops.gate(),releases:ops.data.releases,flags:ops.data.flags,knownIssues:ops.data.issues,requests:ops.data.requests,feedback,coverage:{rawDays:analytics.rawDays,crashes:'Not integrated; errors are not crashes',devices:'Self-reported safe families, no hardware identifiers',retention:'Observed since beta acceptance; retained channel-specific activity only',targets:'Not configured'}};
}
function aggregateReport(report){return{environment:report.environment,channel:report.channel,generatedAt:report.generatedAt,summary:report.summary,retention:report.retention,adoption:{...report.adoption,history:report.adoption.history.map(({tester,...r})=>r)},quality:report.quality,editor:report.editor,errors:report.errors,deviceCoverage:report.deviceCoverage,cohorts:report.cohorts,gate:{status:report.gate.status,marketingReady:report.gate.marketingReady,criticalBugs:report.gate.criticalBugs},feedbackSummary:Object.entries(Object.groupBy(report.feedback,f=>f.category)).map(([category,rows])=>({category,count:rows.length})),coverage:report.coverage}}
module.exports={betaReport,aggregateReport};
