'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {COHORTS,FLAGS,CATEGORIES,OUTCOMES,CHECKS,BLOCKERS,fail,choice,text,keys,context}=require('./schema');
class BetaStore {
 constructor(file,{clock=Date.now,environment='development',channel='DEV',required=channel==='BETA'}={}){
  this.file=file;this.clock=clock;this.environment=environment;this.channel=choice(channel,['DEV','INTERNAL','BETA','PRODUCTION']);this.required=required;
  this.data={environment,channel,testers:[],feedback:[],releases:[],flags:[],issues:[],requests:[],sequence:0};
  try{const saved=JSON.parse(fs.readFileSync(file,'utf8'));if(saved.environment!==environment||saved.channel!==channel||!Array.isArray(saved.testers)||!Array.isArray(saved.releases))throw Error('BETA_STORE_ENVIRONMENT_MISMATCH');this.data=saved}catch(e){if(e.code!=='ENOENT')throw e}
  this.data.devices??=[];this.data.targets??={};
 }
 now(){return new Date(this.clock()).toISOString()}
 save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=this.file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(this.data),{mode:0o600});fs.renameSync(tmp,this.file)}
 mutate(fn){const before=structuredClone(this.data);try{const value=fn();this.save();return value}catch(e){this.data=before;throw e}}
 tester(id){return this.data.testers.find(t=>t.accountId===id)}
 invite(body){if(this.data.testers.length>=10000)throw fail('BETA_CAPACITY_REACHED',409);keys(body,['email','cohort']);const email=text(body.email,254,true).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw fail('INVALID_EMAIL');if(this.data.testers.some(t=>t.email===email))throw fail('TESTER_ALREADY_INVITED',409);return this.mutate(()=>{const t={id:crypto.randomUUID(),email,cohort:choice(body.cohort,COHORTS),status:'INVITED',invitedAt:this.now(),acceptedAt:null,accountId:null,analyticsOptOut:false};this.data.testers.push(t);return t})}
 preflight(email,verified){const t=verified&&this.data.testers.find(t=>t.email===String(email).trim().toLowerCase());if(this.required&&(!t||!['INVITED','ACTIVE'].includes(t.status)))throw fail('BETA_ACCESS_REQUIRED',403);if(t&&['PAUSED','REMOVED'].includes(t.status))throw fail('BETA_ACCESS_PAUSED',403);return t}
 accept(t,id){if(!t)return;if(t.accountId&&t.accountId!==id)throw fail('INVITE_IDENTITY_MISMATCH',403);if(t.status==='INVITED')this.mutate(()=>{t.accountId=id;t.status='ACTIVE';t.acceptedAt=this.now()})}
 assertAccess(id){const t=this.tester(id);if((this.required&&!t)||(t&&t.status!=='ACTIVE'))throw fail('BETA_ACCESS_REQUIRED',403)}
 updateTester(body){keys(body,['id','status','cohort']);const t=this.data.testers.find(t=>t.id===body.id);if(!t)throw fail('TESTER_NOT_FOUND',404);return this.mutate(()=>{if(body.status){choice(body.status,['INVITED','ACTIVE','PAUSED','REMOVED']);if(body.status==='INVITED'&&t.accountId)throw fail('INVITE_ALREADY_ACCEPTED');if(body.status==='ACTIVE'&&!t.accountId)throw fail('INVITE_NOT_ACCEPTED');t.status=body.status}if(body.cohort)t.cohort=choice(body.cohort,COHORTS);return t})}
 enabled(flag,id){choice(flag,FLAGS);const matches=this.data.flags.filter(f=>f.flag===flag),t=this.tester(id);if(matches.some(f=>f.scope==='GLOBAL'&&f.enabled===false))return false;const account=matches.find(f=>f.scope==='ACCOUNT'&&f.target===id),cohort=matches.find(f=>f.scope==='COHORT'&&f.target===t?.cohort),global=matches.find(f=>f.scope==='GLOBAL');return account?.enabled??cohort?.enabled??global?.enabled??!['v3_visible','rig_preview_enabled'].includes(flag)}
 requireFlag(flag,id){if(!this.enabled(flag,id))throw fail('FEATURE_TEMPORARILY_DISABLED',409)}
 setFlag(body){keys(body,['flag','scope','target','enabled','reason']);choice(body.flag,FLAGS);choice(body.scope,['GLOBAL','COHORT','ACCOUNT']);text(body.reason,300,true);if(typeof body.enabled!=='boolean')throw fail('INVALID_FLAG');const target=body.scope==='GLOBAL'?'GLOBAL':body.scope==='COHORT'?choice(body.target,COHORTS):text(body.target,64,true);if(body.scope==='ACCOUNT'&&!this.tester(target))throw fail('TESTER_NOT_FOUND',404);return this.mutate(()=>{this.data.flags=this.data.flags.filter(f=>!(f.flag===body.flag&&f.scope===body.scope&&f.target===target));const value={flag:body.flag,scope:body.scope,target,enabled:body.enabled,reason:body.reason,updatedAt:this.now()};this.data.flags.push(value);return value})}
 observe(id,metadata){const t=this.tester(id);if(!t||t.analyticsOptOut)return;const value=context({...((t.context?.platform===metadata.platform)?t.context:{}),...metadata});if(t.lastActive&&this.clock()-Date.parse(t.lastActive)<60000&&JSON.stringify(t.context)===JSON.stringify(value))return;this.mutate(()=>{t.firstInstall??=this.now();t.lastActive=this.now();t.context=value;t.adoption??=[];if(value.buildNumber&&t.adoption.at(-1)?.buildNumber!==value.buildNumber)t.adoption.push({at:this.now(),version:value.appVersion,buildNumber:value.buildNumber});t.adoption=t.adoption.slice(-100)})}
 feedback(id,body,metadata){if(this.data.feedback.length>=20000)throw fail('FEEDBACK_CAPACITY_REACHED',409);keys(body,['eventId','category','title','description','context','search','diagnosticConsent']);if(!this.tester(id))throw fail('BETA_TESTER_REQUIRED',403);if(typeof body.eventId!=='string'||! /^[a-f0-9-]{36}$/i.test(body.eventId))throw fail('INVALID_EVENT_ID');const existing=this.data.feedback.find(f=>f.eventId===body.eventId&&f.reporter===id);if(existing)return {id:existing.id};if(this.data.feedback.filter(f=>f.reporter===id&&this.clock()-Date.parse(f.createdAt)<86400000).length>=20)throw fail('FEEDBACK_RATE_LIMIT',429);
 const category=choice(body.category,CATEGORIES),title=text(body.title,120,true),description=text(body.description,4000,true),safe=context({...body.context,...metadata});let search=null;
 if(body.search){if(body.diagnosticConsent!==true)throw fail('DIAGNOSTIC_CONSENT_REQUIRED');keys(body.search,['outcome','model','latencyMs','ranks','resultIds']);search={outcome:choice(body.search.outcome,OUTCOMES)};if(body.search.model)search.model=choice(body.search.model,['SERAN_V1','SERAN_V2','SERAN_V3']);if(body.search.latencyMs!=null){if(!Number.isFinite(body.search.latencyMs)||body.search.latencyMs<0||body.search.latencyMs>3600000)throw fail('INVALID_LATENCY');search.latencyMs=body.search.latencyMs}if(body.search.ranks){if(!Array.isArray(body.search.ranks)||body.search.ranks.length>10||body.search.ranks.some(v=>!Number.isInteger(v)||v<1||v>1000))throw fail('INVALID_RANKS');search.ranks=body.search.ranks}if(body.search.resultIds){if(!Array.isArray(body.search.resultIds)||body.search.resultIds.length>10||body.search.resultIds.some(v=>typeof v!=='string'||!/^result-[a-f0-9]{16,64}$/.test(v)))throw fail('OPAQUE_RESULT_IDS_REQUIRED');search.resultIds=body.search.resultIds}}
 return this.mutate(()=>{const bug={id:`HON-${new Date(this.clock()).getUTCFullYear()}-${String(++this.data.sequence).padStart(6,'0')}`,eventId:body.eventId,category,title,description,context:safe,search,reporter:id,channel:this.channel,status:'NEW',severity:'S3',assignedOwner:null,notes:[],createdAt:this.now(),updatedAt:this.now()};this.data.feedback.push(bug);return{id:bug.id}})
 }
 triage(body){keys(body,['id','status','severity','assignedOwner','note']);const bug=this.data.feedback.find(f=>f.id===body.id);if(!bug)throw fail('BUG_NOT_FOUND',404);return this.mutate(()=>{if(body.status)bug.status=choice(body.status,['NEW','TRIAGED','IN_PROGRESS','FIXED','VERIFIED','CLOSED']);if(body.severity)bug.severity=choice(body.severity,['S1','S2','S3','S4']);if(body.assignedOwner!==undefined)bug.assignedOwner=text(body.assignedOwner,64);if(body.note)bug.notes.push({text:text(body.note,2000,true),at:this.now()});bug.updatedAt=this.now();return bug})}
 release(body){keys(body,['platform','version','buildNumber','commit','channel','status','internalNotes','testerNotes','updateLevel','minimumBuild']);if(!/^\d[\w.-]{0,23}$/.test(body.version)||!/^\d{1,10}$/.test(body.buildNumber)||! /^[a-f0-9]{7,40}$/.test(body.commit))throw fail('INVALID_RELEASE');if(body.channel!==this.channel)throw fail('CHANNEL_MISMATCH',403);const platform=choice(body.platform||'ANDROID',['ANDROID','WEB_TEST','IOS','ALL']);if(this.data.releases.some(r=>r.buildNumber===body.buildNumber&&(r.platform||'ANDROID')===platform))throw fail('BUILD_ALREADY_REGISTERED',409);const updateLevel=choice(body.updateLevel||'OPTIONAL',['OPTIONAL','RECOMMENDED','REQUIRED']);if(updateLevel==='REQUIRED'&&!/^\d{1,10}$/.test(body.minimumBuild))throw fail('MINIMUM_BUILD_REQUIRED');return this.mutate(()=>{const r={id:crypto.randomUUID(),platform,version:body.version,buildNumber:body.buildNumber,commit:body.commit,channel:this.channel,status:choice(body.status||'DRAFT',['DRAFT','TESTING','RELEASED','WITHDRAWN']),internalNotes:text(body.internalNotes,4000,true),testerNotes:text(body.testerNotes,4000,true),updateLevel,minimumBuild:body.minimumBuild||null,releasedAt:this.now(),checks:{},assets:[]};this.data.releases.push(r);return r})}
 check(body,actor){keys(body,['releaseId','check','passed','evidence']);const r=this.data.releases.find(r=>r.id===body.releaseId);if(!r)throw fail('RELEASE_NOT_FOUND',404);choice(body.check,CHECKS);if(typeof body.passed!=='boolean')throw fail('INVALID_CHECK');return this.mutate(()=>{r.checks[body.check]={passed:body.passed,evidence:text(body.evidence,500,true),actor,at:this.now()};return this.gate(r)})}
 gate(r=this.current()){const missing=CHECKS.filter(k=>r?.checks[k]?.passed!==true),critical=this.data.feedback.filter(f=>f.severity==='S1'&&!['VERIFIED','CLOSED'].includes(f.status)).length+this.data.issues.filter(i=>i.severity==='S1'&&i.status==='OPEN').length;const marketingReady=!!r&&!critical&&['real_photo_demo','android_actions_pass','artifact_exists','auth_verified','search_ledger','editor_save','privacy_check'].every(k=>r.checks[k]?.passed===true);return{status:!r||critical||BLOCKERS.some(k=>missing.includes(k))?'NO-GO':missing.length?'CONDITIONAL':'GO',missing,criticalBugs:critical,marketingReady,demoA:r?.checks.real_photo_demo?.passed===true,demoB:r?.demoB?.passed===true,demoC:r?.checks.editor_save?.passed===true,assets:marketingReady?(r.assets||[]).filter(a=>a.approved):[]}}
 device(body){keys(body,['id','manufacturer','modelFamily','osVersion','ramClass','vulkan','capabilityClass','status','evidence']);const safe=context(Object.fromEntries(Object.entries(body).filter(([k])=>!['id','status','evidence'].includes(k))));const status=choice(body.status,['NOT_TESTED','TESTED','ISSUE']);if(!safe.manufacturer||!safe.modelFamily)throw fail('DEVICE_FAMILY_REQUIRED');if(body.id&&!this.data.devices.some(d=>d.id===body.id))throw fail('DEVICE_NOT_FOUND',404);return this.mutate(()=>{const value={id:body.id||crypto.randomUUID(),...safe,status,evidence:text(body.evidence||'',500,status!=='NOT_TESTED'),updatedAt:this.now()};this.data.devices=this.data.devices.filter(d=>d.id!==value.id);this.data.devices.push(value);return value})}
 target(body){keys(body,['metric','value']);choice(body.metric,['invited','activated','dau','successfulSearches','searchFeedback','crashFreeSessions','searchesPerTester','studioInterest','memoryPassInterest']);if(body.value!==null&&(!Number.isFinite(body.value)||body.value<0||body.value>100000000))throw fail('INVALID_TARGET');return this.mutate(()=>{if(body.value===null)delete this.data.targets[body.metric];else this.data.targets[body.metric]=body.value;return this.data.targets})}
 releaseStatus(body){keys(body,['id','status','reason']);const r=this.data.releases.find(r=>r.id===body.id);if(!r)throw fail('RELEASE_NOT_FOUND',404);text(body.reason,500,true);return this.mutate(()=>{r.status=choice(body.status,['DRAFT','TESTING','RELEASED','WITHDRAWN']);r.statusReason=body.reason;r.updatedAt=this.now();return r})}
 asset(body,actor){keys(body,['releaseId','kind','reference','claim','approved']);const r=this.data.releases.find(r=>r.id===body.releaseId);if(!r)throw fail('RELEASE_NOT_FOUND',404);if(typeof body.approved!=='boolean')throw fail('INVALID_APPROVAL');return this.mutate(()=>{const value={id:crypto.randomUUID(),kind:choice(body.kind,['SCREENSHOT','DEMO_A','DEMO_B','DEMO_C','CLAIM']),reference:text(body.reference,300,true),claim:text(body.claim,500,true),approved:body.approved,actor,at:this.now()};r.assets.push(value);if(value.kind==='DEMO_B')r.demoB={passed:value.approved,evidence:value.reference};return value})}
 current(){return this.data.releases.filter(r=>r.status!=='WITHDRAWN').at(-1)}
 knownIssue(body){keys(body,['id','title','testerText','severity','platform','version','status']);if(body.id&&!this.data.issues.some(i=>i.id===body.id))throw fail('ISSUE_NOT_FOUND',404);return this.mutate(()=>{const issue={id:body.id||crypto.randomUUID(),title:text(body.title,120,true),testerText:text(body.testerText||'',1000),severity:choice(body.severity,['S1','S2','S3','S4']),platform:choice(body.platform||'ALL',['ALL','ANDROID','WEB_TEST','IOS']),version:text(body.version||'',24),status:choice(body.status||'OPEN',['OPEN','RESOLVED']),createdAt:this.now()};this.data.issues=this.data.issues.filter(i=>i.id!==issue.id);this.data.issues.push(issue);return issue})}
 request(id,body){keys(body,['type']);choice(body.type,['ACCOUNT_DELETION','BETA_REMOVAL','ANALYTICS_OPT_OUT']);return this.mutate(()=>{let row=this.data.requests.find(r=>r.accountId===id&&r.type===body.type&&r.status==='OPEN');if(!row){row={id:crypto.randomUUID(),accountId:id,type:body.type,status:'OPEN',at:this.now()};this.data.requests.push(row)}const t=this.tester(id);if(t&&body.type==='ANALYTICS_OPT_OUT')t.analyticsOptOut=true;if(t&&body.type==='BETA_REMOVAL')t.status='REMOVED';return row})}
 resolveRequest(body){keys(body,['id','status','note']);const row=this.data.requests.find(r=>r.id===body.id);if(!row)throw fail('REQUEST_NOT_FOUND',404);return this.mutate(()=>{row.status=choice(body.status,['IN_REVIEW','FULFILLED','DECLINED']);row.note=text(body.note,2000,true);row.updatedAt=this.now();return row})}
 config(id,metadata={}){const r=this.data.releases.filter(r=>r.status==='RELEASED'&&(!metadata.platform||metadata.platform==='UNKNOWN'||(r.platform||'ANDROID')===metadata.platform||r.platform==='ALL')).at(-1),t=this.tester(id),build=Number(metadata.buildNumber);return{channel:this.channel,betaRequired:this.required,tester:t?{status:t.status,cohort:t.cohort,analyticsOptOut:t.analyticsOptOut}:null,flags:Object.fromEntries(FLAGS.map(f=>[f,this.enabled(f,id)])),release:r?{version:r.version,buildNumber:r.buildNumber,testerNotes:r.testerNotes,updateLevel:r.updateLevel,minimumBuild:r.minimumBuild,updateNeeded:!build||build<Number(r.buildNumber)}:null,knownIssues:this.data.issues.filter(i=>i.status==='OPEN'&&i.testerText&&(!i.version||i.version===metadata.appVersion)&&(i.platform==='ALL'||i.platform===metadata.platform)).map(i=>({text:i.testerText,severity:i.severity}))}}
}
module.exports={BetaStore};
