import React,{useEffect,useState,useRef} from 'react';
import {Alert,Pressable,ScrollView,Text,TextInput,Switch,StyleSheet,Platform} from 'react-native';
import {useNavigation} from '@react-navigation/native';
import {honorableNative} from '../native/HonorableNative';
type BetaConfig={tester?:{status:string};release?:{version:string;updateLevel:string;updateNeeded:boolean;testerNotes:string};knownIssues?:{text:string}[]};
const categories=['BUG','SEARCH RESULT','VIDEO SEARCH','EDITOR','PASS/USAGE','STUDIO','PERFORMANCE','UI','OTHER'];
const outcomes=['CORRECT','WRONG','NOT_FOUND','TIMESTAMP_WRONG','TOO_SLOW'];
const request=async(route:string,body?:object)=>honorableNative.accountSessionAction('/v1/beta/'+route,body?JSON.stringify(body):null) as unknown as Promise<any>;
export function BetaFeedbackScreen(){const navigation=useNavigation();const[config,setConfig]=useState<BetaConfig|null>(null),[category,setCategory]=useState('BUG'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[consent,setConsent]=useState(false),[outcome,setOutcome]=useState('WRONG'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const eventId=useRef('');
 useEffect(()=>{request('config').then(setConfig).catch(()=>setMessage('Beta status unavailable. Connect to your configured account service.'))},[]);
 async function submit(){setBusy(true);try{if(!eventId.current)eventId.current='xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.floor(Math.random()*16);return(c==='x'?r:(r&3)|8).toString(16)});const result=await request('feedback',{eventId:eventId.current,category,title,description,context:{screen:'BetaFeedback',platform:Platform.OS==='android'?'ANDROID':'IOS'},...(consent?{diagnosticConsent:true,search:{outcome}}:{})});setMessage('Feedback received: '+result.id);eventId.current='';setTitle('');setDescription('')}catch{setMessage('Feedback could not be sent. Check your connection and active beta membership; your text remains here.')}finally{setBusy(false)}}
 function privacy(type:string){Alert.alert('Send account request',type==='ANALYTICS_OPT_OUT'?'Stop optional analytics collection?':'Submit this request for review? Beta removal ends beta access.',[{text:'Cancel',style:'cancel'},{text:'Submit',onPress:()=>request('request',{type}).then(()=>setMessage('Request recorded. Purchase records are handled separately.')).catch(()=>setMessage('Request could not be sent.'))}])}
 return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={()=>navigation.goBack()}><Text style={styles.text}>Back</Text></Pressable><Text style={styles.title}>Beta feedback</Text><Text style={styles.text}>Share a short report. No media, search text, project files or credentials are attached automatically. Only include information you intend to share with the internal team.</Text>{config?.release&&<Text style={styles.text}>{config.release.updateNeeded?config.release.updateLevel+' update available: ': 'Current release: '}{config.release.version}{'\n'}{config.release.testerNotes}</Text>}{config?.knownIssues?.map((issue,i)=><Text key={i} style={styles.text}>{issue.text}</Text>)}<Text style={styles.text}>Category: {category}</Text>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)}><Text style={styles.choice}>{c===category?'● ':''}{c}</Text></Pressable>)}<TextInput accessibilityLabel="Feedback title" placeholder="Short title" placeholderTextColor="#888" value={title} onChangeText={setTitle} maxLength={120} style={styles.input}/><TextInput accessibilityLabel="Feedback description" placeholder="What happened? What did you expect?" placeholderTextColor="#888" multiline value={description} onChangeText={setDescription} maxLength={4000} style={styles.input}/><Text style={styles.text}>Include an explicit search-quality assessment (optional)</Text><Switch value={consent} onValueChange={setConsent}/>{consent&&outcomes.map(o=><Pressable key={o} onPress={()=>setOutcome(o)}><Text style={styles.choice}>{outcome===o?'● ':''}{o}</Text></Pressable>)}<Text style={styles.text}>Screenshots and file attachments are not enabled in this build. You can describe the issue without sharing private media.</Text><Pressable disabled={busy||!title.trim()||!description.trim()||config?.tester?.status!=='ACTIVE'} onPress={submit}><Text style={styles.choice}>{busy?'Sending…':'Send feedback'}</Text></Pressable><Text accessibilityLiveRegion="polite" style={styles.text}>{message}</Text>{['ACCOUNT_DELETION','BETA_REMOVAL','ANALYTICS_OPT_OUT'].map(type=><Pressable key={type} onPress={()=>privacy(type)}><Text style={styles.choice}>{type.replaceAll('_',' ')}</Text></Pressable>)}</ScrollView>}
const styles=StyleSheet.create({page:{padding:24,paddingTop:48,paddingBottom:80,backgroundColor:'#080808',gap:12},title:{color:'#fff',fontSize:28,fontWeight:'700'},text:{color:'#b8b8b8',lineHeight:21},choice:{color:'#a9d8c5',paddingVertical:8},input:{color:'#fff',backgroundColor:'#171717',padding:12,borderRadius:8}});
