import React,{useState}from'react';
import{Alert,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{useMemoryPass}from'../passes/MemoryPassContext';
import{memoryPasses}from'../passes/catalog';
import{useNavigation}from'@react-navigation/native';
export const productStyles=StyleSheet.create({safe:{flex:1,backgroundColor:'#050505'},content:{padding:20,paddingBottom:110,gap:14},title:{fontSize:34,fontWeight:'700',color:'#fff'},heading:{fontSize:19,fontWeight:'600',color:'#fff',marginTop:12},body:{color:'#aaa',lineHeight:21},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{backgroundColor:'#19191b',borderRadius:20,padding:16,width:'48%',gap:8},number:{color:'#fff',fontSize:25,fontWeight:'600'},button:{padding:14,borderRadius:16,backgroundColor:'#242427',minHeight:48},label:{color:'#fff'},row:{paddingVertical:12,borderBottomWidth:1,borderColor:'#29292c',gap:5}});
const s=productStyles;
export function ProductPage({title,children}:{title:string;children:React.ReactNode}){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>{title}</Text>{children}</ScrollView></SafeAreaView>}
export function CreditBalances(){const{account}=useMemoryPass();return <View style={s.grid}><View style={s.card}><Text style={s.body}>FREE THIS MONTH</Text><Text style={s.number}>{account?.freeMonthlyRemaining??'—'} / {account?.freeMonthlyTotal??'—'}</Text></View><View style={s.card}><Text style={s.body}>YOUR MEMORY CREDITS</Text><Text style={s.number}>{account?.balance??'—'}</Text><Text style={s.body}>Never expires</Text></View></View>}
export function ProductPassScreen(){const[all,setAll]=useState(false);const{restore}=useMemoryPass();return <ProductPage title="Memory Passes"><Text style={s.body}>Buy once. Use whenever you need it.{ '\n'}Purchased Memory Credits never expire.</Text><CreditBalances/><Text style={s.heading}>Recommended Memory Passes</Text><Text style={s.body}>Reference USD prices. Purchases are not enabled yet.</Text><View style={s.grid}>{memoryPasses.slice(0,all?31:20).map(p=><Pressable key={p.id} style={s.card} onPress={()=>Alert.alert('Memory Pass','Store purchases are not connected. No payment collected.')}><Text style={s.number}>{p.credits.toLocaleString()}</Text><Text style={s.label}>Memory Credits</Text><Text style={s.label}>${p.referenceUsd} USD</Text><Text style={s.body}>One-time purchase · never expires</Text></Pressable>)}</View><Pressable style={s.button} onPress={()=>setAll(!all)}><Text style={s.label}>{all?'Show recommended':'Show all 31 passes'}</Text></Pressable><Pressable style={s.button} onPress={()=>restore().catch(e=>Alert.alert('Restore',e.message))}><Text style={s.label}>Restore purchases</Text></Pressable></ProductPage>}
export function ProductUsageScreen(){const{account}=useMemoryPass();const[limit,setLimit]=useState(20);const usage=account?.usage;return <ProductPage title="Memory Credits"><CreditBalances/><Text style={s.body}>Resets {account?.nextResetAt?new Date(account.nextResetAt).toLocaleDateString():'—'}{ '\n'}Free monthly credits do not roll over.</Text><Text style={s.heading}>This month</Text><Text style={s.body}>Free credits used: {usage?.month.freeCreditsUsed??0}{'\n'}Purchased credits used: {usage?.month.purchasedCreditsUsed??0}{'\n'}Search count: {usage?.month.searchCount??0}</Text><Text style={s.heading}>By model</Text>{['FAST','VIDEO','TURBO'].map((n,i)=><Text key={n} style={s.body}>{n} searches: {usage?.byModel[`SERAN_V${i+1}`]??0}</Text>)}<Text style={s.heading}>All time</Text><Text style={s.body}>Searches completed: {usage?.allTime.searchesCompleted??0}{'\n'}Purchased credits used: {usage?.allTime.purchasedCreditsUsed??0}{'\n'}Passes purchased: {usage?.allTime.passesPurchased??0}</Text><Text style={s.heading}>Honorable Studio · {account?.subscription.status??'NONE'}</Text><Text style={s.body}>Studio AI allowance is separate and not configured.</Text><Text style={s.heading}>Recent usage ledger</Text>{account?.transactions.slice(0,limit).map(t=><View style={s.row} key={t.id}><Text style={s.label}>{t.description}</Text><Text style={s.body}>{new Date(t.createdAt).toLocaleDateString()} · {t.type==='DEBIT'?`${t.freeSpent??0} Free + ${t.purchasedSpent??-t.credits} Purchased used`:`${t.credits>0?'+':''}${t.credits} credits`}</Text></View>)}{(account?.transactions.length??0)>limit&&<Pressable style={s.button} onPress={()=>setLimit(limit+20)}><Text style={s.label}>Load more</Text></Pressable>}</ProductPage>}
export function StudioScreen(){const{account}=useMemoryPass();const navigation=useNavigation<any>();const active=account?.subscription.status==='ACTIVE';return <ProductPage title="Honorable Studio"><Text style={s.body}>Professional AI photo, video and spatial editing — designed for mobile.</Text><Text style={s.heading}>Photo · Free tools</Text><Text style={s.body}>Crop, rotate, adjust, undo, redo, reset, before/after and save as copy.</Text><Pressable style={s.button} onPress={()=>navigation.navigate('Memories')}><Text style={s.label}>Choose a memory to edit</Text></Pressable><Text style={s.heading}>Advanced creative work</Text>{['Generative Fill','AI Expansion','Advanced rig animation','Subject selection','Content-aware Move / Patch','Smart Filters','RAW controls','AI Relighting','Smart Layers','Video Sequence','Camera Tracking','3D video','Nodes / Compositing','Geometry','AI video','Code'].map(name=><Pressable key={name} style={s.button} onPress={()=>Alert.alert(name,active?'Coming Soon. This engine is not implemented.':'This advanced capability requires Honorable Studio and is Coming Soon.')}><Text style={s.label}>{active?'':'🔒 '}{name}</Text><Text style={s.body}>Coming Soon</Text></Pressable>)}<Text style={s.body}>Basic still-photo pose: Partial. Person segmentation and image deformation are not implemented.</Text><Pressable style={s.button} onPress={()=>Alert.alert('Honorable Studio','Monthly membership pricing is not finalized. Store subscriptions are not connected.')}><Text style={s.label}>{active?'Studio active':'Unlock Honorable Studio'}</Text></Pressable></ProductPage>}
