import React from'react';
import{Linking,Pressable,ScrollView,StyleSheet,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{Check,ChevronRight,CircleUserRound,FileText,Heart,Images,ShieldCheck,Sparkles}from'lucide-react-native';
import{useNavigation}from'@react-navigation/native';
import type{NativeStackNavigationProp}from'@react-navigation/native-stack';
import{Text}from'@/components/ui/text';
import type{RootStackParamList}from'../navigation/types';

const p={bg:'#F5F5F5',ink:'#0B0B0C',muted:'#686868',soft:'#DEDEDE',strong:'#C8C8C8',line:'#CECECE',white:'#FFFFFF'};
function Row({icon,title,detail,onPress}:{icon:React.ReactNode;title:string;detail:string;onPress?:()=>void}){return <Pressable accessibilityRole="button" disabled={!onPress} onPress={onPress} style={[s.row,!onPress&&s.disabled]}><View style={s.rowIcon}>{icon}</View><View style={s.rowCopy}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowDetail}>{detail}</Text></View><ChevronRight color={p.muted} size={18}/></Pressable>}

export function SettingsScreen(){const navigation=useNavigation<NativeStackNavigationProp<RootStackParamList>>();return <SafeAreaView edges={['top']} style={s.safe}><ScrollView contentContainerStyle={s.content}>
  <View style={s.brand}><View style={s.mark}><Text style={s.markText}>h</Text></View><View><Text style={s.brandName}>Honorable</Text><Text style={s.brandDetail}>Your preferences</Text></View><View style={s.profile}><CircleUserRound color={p.ink} size={18}/></View></View>
  <View style={s.intro}><Text style={s.eyebrow}>SETTINGS</Text><Text accessibilityRole="header" style={s.title}>Made for you.</Text><Text style={[s.title,s.titleMuted]}>Private by design.</Text><Text style={s.subtitle}>Control access, plans, and the details that make Honorable yours.</Text></View>
  <View style={s.privacyCard}><View style={s.privacyIcon}><ShieldCheck color={p.ink} size={22}/></View><View style={s.privacyCopy}><Text style={s.privacyLabel}>PRIVACY</Text><Text style={s.privacyTitle}>On-device by default</Text><Text style={s.privacyDetail}>Your searches and media stay on this phone.</Text></View><View style={s.check}><Check color={p.ink} size={15}/></View></View>
  <View style={s.quickGrid}><Pressable style={s.quick} onPress={()=>Linking.openSettings()}><Images color={p.ink} size={20}/><Text style={s.quickLabel}>PHOTO ACCESS</Text><Text style={s.quickTitle}>Managed by device</Text><Text style={s.quickDetail}>Choose photos & videos</Text></Pressable><Pressable style={[s.quick,s.quickStrong]} onPress={()=>navigation.navigate('Usage')}><Heart color={p.ink} size={20}/><Text style={s.quickLabel}>YOUR PLAN</Text><Text style={s.quickTitle}>Usage & limits</Text><Text style={s.quickDetail}>See what is included</Text></Pressable></View>
  <Text style={s.sectionLabel}>HONORABLE</Text><View style={s.rows}><Row icon={<Sparkles color={p.white} size={16}/>} title="Plans" detail="Compare available options" onPress={()=>navigation.navigate('Plans')}/><Row icon={<FileText color={p.white} size={16}/>} title="About & legal" detail="Terms of Service and Privacy Policy" onPress={()=>navigation.navigate('AboutLegal')}/><Row icon={<ShieldCheck color={p.white} size={16}/>} title="Engine health" detail="Developer diagnostics"/></View>
</ScrollView></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:p.bg},content:{paddingHorizontal:17,paddingTop:10,paddingBottom:104},brand:{height:58,flexDirection:'row',alignItems:'center'},mark:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center',backgroundColor:p.ink},markText:{color:p.white,fontSize:22,fontWeight:'700'},brandName:{marginLeft:10,color:p.ink,fontSize:13,fontWeight:'700'},brandDetail:{marginLeft:10,color:p.muted,fontSize:8},profile:{marginLeft:'auto',width:38,height:38,borderRadius:19,borderWidth:1,borderColor:p.line,backgroundColor:p.white,alignItems:'center',justifyContent:'center'},intro:{marginTop:12},eyebrow:{color:p.muted,fontSize:9,fontWeight:'600',letterSpacing:1.2},title:{marginTop:8,color:p.ink,fontSize:40,lineHeight:38,fontWeight:'700',letterSpacing:-1.7},titleMuted:{marginTop:-2,color:'#898989'},subtitle:{maxWidth:315,marginTop:7,color:p.muted,fontSize:12,lineHeight:17},privacyCard:{height:126,marginTop:16,padding:14,borderRadius:38,backgroundColor:p.ink,flexDirection:'row',alignItems:'center'},privacyIcon:{width:62,height:62,borderRadius:31,backgroundColor:p.white,alignItems:'center',justifyContent:'center'},privacyCopy:{flex:1,paddingLeft:14},privacyLabel:{color:'#AEB7C2',fontSize:8,fontWeight:'600',letterSpacing:1},privacyTitle:{marginTop:6,color:p.white,fontSize:18,fontWeight:'700'},privacyDetail:{maxWidth:205,marginTop:5,color:'#AAAAAA',fontSize:9,lineHeight:12},check:{width:28,height:28,borderRadius:14,backgroundColor:p.white,alignItems:'center',justifyContent:'center'},quickGrid:{marginTop:9,flexDirection:'row',gap:8},quick:{width:'48.8%',height:124,padding:16,borderRadius:31,borderWidth:1,borderColor:p.line,backgroundColor:p.soft},quickStrong:{backgroundColor:p.strong},quickLabel:{marginTop:12,color:p.muted,fontSize:8,fontWeight:'600',letterSpacing:.8},quickTitle:{marginTop:5,color:p.ink,fontSize:16,fontWeight:'700'},quickDetail:{marginTop:4,color:p.muted,fontSize:8},sectionLabel:{marginTop:18,marginBottom:7,color:p.muted,fontSize:8,fontWeight:'600',letterSpacing:1},rows:{borderRadius:28,overflow:'hidden',borderWidth:1,borderColor:p.line,backgroundColor:'#EEEEEE'},row:{minHeight:66,paddingHorizontal:10,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:p.line},disabled:{opacity:.72},rowIcon:{width:38,height:38,borderRadius:19,backgroundColor:p.ink,alignItems:'center',justifyContent:'center'},rowCopy:{flex:1,paddingLeft:10},rowTitle:{color:p.ink,fontSize:11,fontWeight:'700'},rowDetail:{marginTop:4,color:p.muted,fontSize:8}});
