const q=new URLSearchParams(location.search);const id=q.get('screen')||'concept-c';
const media=Array.from({length:9},(_,i)=>`<div class="media m${i}">${i===8?'<span>▶ 2:14</span>':''}</div>`).join('');
const search=(value='')=>`<div class="search"><b>⌕</b><span class="${value?'filled':''}">${value||'Describe a memory…'}</span>${value?'<i>×</i>':''}</div>`;
const nav=(active='Home')=>`<div class="nav">${[['⌂','Home'],['▦','Memories'],['◫','Storage'],['⚙','Settings']].map(([icon,label])=>`<span class="${label===active?'active':''}">${icon}<small>${label}</small></span>`).join('')}</div>`;
const concepts={
 'concept-a':{klass:'mono',eyebrow:'CONCEPT A · BLACK / WHITE',title:'Find a moment.',sub:'Describe anything you remember.'},
 'concept-b':{klass:'blue',eyebrow:'CONCEPT B · TRANSPARENT BLUE',title:'Find a moment.',sub:'Describe anything you remember.'},
 'concept-c':{klass:'hybrid',eyebrow:'CONCEPT C · HYBRID',title:'Find a moment.',sub:'Describe anything you remember.'}
};
function home(c=concepts['concept-c']){return `<main class="phone ${c.klass}"><header><b>HONORABLE</b><span>On-device</span></header><section class="intro home-intro"><em>${c.eyebrow}</em><h1>${c.title}</h1><p>${c.sub}</p></section>${search()}<button class="mode">⌕ &nbsp; Quick <i>⌄</i></button><div class="result-head home-recent"><b>Recent</b><span>Your library</span></div><div class="grid home-grid">${media}</div>${nav()}</main>`}
function results(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>On-device</span></header>${search('white dog at the beach')}<button class="mode">⌕ &nbsp; Quick <i>⌄</i></button><div class="result-head compact"><b>24 matches</b><span>Best first</span></div><div class="filters"><b>All</b><span>Photos</span><span>Videos</span><span>Date</span></div><div class="grid results">${media}</div>${nav()}</main>`}
function viewer(){return `<main class="phone viewer"><div class="hero-media m0"></div><div class="viewer-top"><b>‹</b><span>1 of 24</span><i></i></div><div class="viewer-bottom"><b>White dog at the beach</b><small>Strong match · photo</small></div></main>`}
function indexing(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>On-device</span></header><section class="intro"><h1>Your library is taking shape.</h1><p>Search what’s ready while the rest is prepared.</p></section>${search()}<div class="index-card"><div><b>Preparing your library</b><span>8,421 of 12,540</span></div><i><u></u></i></div><div class="grid faded">${media}</div>${nav()}</main>`}
function empty(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>On-device</span></header>${search('purple elephant in my kitchen')}<div class="empty"><b>No clear match yet</b><p>Try a color, place, date, object, or visible text.</p><button>Clear search</button></div>${nav()}</main>`}
function onboarding(){return `<main class="phone hybrid onboarding"><header><b>HONORABLE</b></header><div class="onboard-grid grid">${media}</div><div class="onboard-copy"><em>PRIVATE PHOTO SEARCH</em><h1>Find any photo by describing it.</h1><p>Your photos stay on this device.</p><button>Choose photos & videos</button></div></main>`}
function settings(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>Settings</span></header><section class="intro"><h1>Simple by design.</h1><p>Privacy, plans, appearance, and legal.</p></section><div class="settings"><div><b>Photo access</b><span>Managed by device ›</span></div><div><b>Usage</b><span>Plan and limits ›</span></div><div><b>Plans</b><span>Compare options ›</span></div><hr><div><b>About & legal</b><span>Terms & privacy ›</span></div></div>${nav('Settings')}</main>`}
function storage(){return `<main class="phone hybrid"><header><b>STORAGE</b><span>On-device</span></header><section class="intro storage-intro"><h1>Your library,<br>on device.</h1><p>See what is ready to search.</p></section><div class="storage-card"><div><i>◫</i><span><b>Index ready</b><small>12,540 media ready</small></span><strong>100%</strong></div><u><em></em></u></div><div class="storage-metrics"><div><small>INDEXED MEDIA</small><b>12,540</b></div><div><small>PHOTO ACCESS</small><b>Selected</b></div><div><small>INDEX STORAGE</small><b>On device</b></div><div><small>CACHE SIZE</small><b>Not measured</b></div></div><div class="safe-storage">✓ <span><b>Your originals stay safe</b><small>Reindexing only rebuilds Honorable’s private index.</small></span></div><div class="storage-actions"><small>LIBRARY</small><div><b>Reindex library</b><span>Rebuild search index only ›</span></div><div><b>Manage photo access</b><span>Device settings ›</span></div></div>${nav('Storage')}</main>`}
const legacyDock=active=>`<nav class="legacy-dock">${[['⌂','Home'],['◎','Memories'],['✦','Terms'],['↻','Activity'],['⚙','Settings']].map(x=>`<span class="${x[1]===active?'active':''}"><i>${x[0]}</i><small>${x[1]}</small></span>`).join('')}</nav>`;
function legacyHome(){return `<main class="phone legacy mono"><div class="legacy-brand"><b>h</b><span><strong>Honorable</strong><small>Private intelligence</small></span><em>●&nbsp; On device</em></div><section class="legacy-hero"><div class="legacy-bubbles"><i></i><i></i><i></i><i></i></div><small>● &nbsp; YOUR LIFE, SEARCHABLE</small><h1>Find what<br><em>matters.</em></h1><p>Describe a moment the way you remember it.<br>Honorable finds it privately, right here.</p><div class="legacy-search"><i>✦</i><span><small>Ask your memories</small><b>A white beach with tall grass</b></span><em>↗</em></div></section><div class="legacy-bento"><div><i>◎</i><span><b>Memories</b><small>Find any moment</small></span><em>↗</em></div><div><i>✦</i><span><b>Terms AI</b><small>Make fine print clear</small></span><em>↗</em></div></div><div class="legacy-private"><i>⌁</i><span><b>Yours stays yours</b><small>Search and media never leave this phone.</small></span><em>✓</em></div>${legacyDock('Home')}</main>`}
function legacyMemories(){return `<main class="phone legacy legacy-memories mono"><div class="legacy-memory-ambient"><i></i><i></i></div><div class="legacy-brand"><b>h</b><span><strong>Honorable</strong><small>Memory space</small></span><em>●&nbsp; On device</em></div><section class="legacy-memory-intro"><small>PRIVATE MEMORY SEARCH</small><h1>What do you<br><em>remember?</em></h1><p>A color, a place, a tiny detail—start anywhere.</p></section><div class="legacy-memory-search">⌕ <span>Start describing…</span><b>↗</b></div><div class="legacy-section-title"><b>Start anywhere</b><small>Made for your library</small></div><div class="legacy-prompt feature beach"><i>⌕</i><span><small>TRY A SCENE</small><b>White beach<br>with tall grass</b><em>Place + texture + color</em></span></div><div class="legacy-prompt-row"><div class="legacy-prompt car"><i>◒</i><span><small>COLOR + WEATHER</small><b>Red car<br>in snow</b></span></div><div class="legacy-prompt cake"><i>✦</i><span><small>OBJECT + LIGHT</small><b>Birthday cake<br>by a window</b></span></div></div><div class="legacy-local"><i>✓</i><span><b>Private by default</b><small>Photos and searches stay on this device.</small></span><em>9,812 ready</em></div>${legacyDock('Memories')}</main>`}
const selected={klass:'mono',eyebrow:'PRIVATE PHOTO SEARCH',title:'Find a moment.',sub:'Describe anything you remember.'};
const screens={'01-home':legacyHome,'02-memories':legacyMemories,'concept-a':()=>home(concepts['concept-a']),'concept-b':()=>home(concepts['concept-b']),'concept-c':()=>home(concepts['concept-c']),'selected-home':()=>home(selected),'selected-results':results,'selected-viewer':viewer,'selected-indexing':indexing,'selected-empty':empty,'selected-onboarding':onboarding,'selected-settings':settings,'selected-storage':storage,'selected-small':()=>`<div class="device-note">SMALL ANDROID · 360 × 800</div>${home(selected)}`,'selected-large':()=>`<div class="device-note">LARGE PHONE · 480 × 1040</div>${results()}`};
document.body.innerHTML=(screens[id]||screens['concept-c'])();
