const q=new URLSearchParams(location.search);const id=q.get('screen')||'01-home';
const media=Array.from({length:9},(_,i)=>`<div class="media m${i}">${i===8?'<span>▶ 2:14</span>':''}</div>`).join('');
const search=(value='')=>`<div class="search"><b>⌕</b><span class="${value?'filled':''}">${value||'Describe a memory…'}</span>${value?'<i>×</i>':''}</div>`;
const nav=(active='Home')=>`<div class="nav">${[['⌂','Home'],['▦','Memories'],['◫','Storage'],['⚙','Settings']].map(([icon,label])=>`<span class="${label===active?'active':''}">${icon}<small>${label}</small></span>`).join('')}</div>`;
const concepts={
 'concept-a':{klass:'mono',eyebrow:'CONCEPT A · BLACK / WHITE',title:'Find a moment.',sub:'Describe anything you remember.'},
 'concept-b':{klass:'blue',eyebrow:'CONCEPT B · TRANSPARENT BLUE',title:'Find a moment.',sub:'Describe anything you remember.'},
 'concept-c':{klass:'hybrid',eyebrow:'CONCEPT C · HYBRID',title:'Find a moment.',sub:'Describe anything you remember.'}
};
function home(c=concepts['concept-c']){return `<main class="phone ${c.klass}"><header><b>HONORABLE</b><span>On-device</span></header><section class="intro home-intro"><em>${c.eyebrow}</em><h1>${c.title}</h1><p>${c.sub}</p></section>${search()}<button class="mode">⌕ &nbsp; Quick <i>⌄</i></button><div class="result-head home-recent"><b>Recent</b><span>Your library</span></div><div class="grid home-grid">${media}</div>${nav()}</main>`}
function results(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>On-device</span></header>${search('white dog at the beach')}<button class="mode">⌕ &nbsp; Quick <i>⌄</i></button><div class="result-head compact"><b>24 matches</b><span>Best first</span></div><div class="filters"><b>All</b><span>Photos</span><span>Videos</span><span>Date</span></div><div class="grid results">${media}</div>${nav()}</main>`}
function viewer(){return `<main class="phone viewer"><div class="hero-media m0"></div><div class="viewer-top"><b>‹</b><span>1 of 24</span><i></i></div><div class="viewer-bottom"><b>White dog at the beach</b><small>Strong match · photo</small></div></main>`}
function indexing(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>On-device</span></header><section class="intro"><h1>Your library is taking shape.</h1><p>Search what’s ready while the rest is prepared.</p></section>${search()}<div class="index-card"><div><b>Preparing your library</b><span>8,421 of 12,540</span></div><i><u></u></i></div><div class="grid faded">${media}</div>${nav()}</main>`}
function empty(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>On-device</span></header>${search('purple elephant in my kitchen')}<div class="empty"><b>No clear match yet</b><p>Try a color, place, date, object, or visible text.</p><button>Clear search</button></div>${nav()}</main>`}
function onboarding(){return `<main class="phone hybrid onboarding"><header><b>HONORABLE</b></header><div class="onboard-grid grid">${media}</div><div class="onboard-copy"><em>PRIVATE PHOTO SEARCH</em><h1>Find any photo by describing it.</h1><p>Your photos stay on this device.</p><button>Choose photos & videos</button></div></main>`}
function settings(){return `<main class="phone hybrid"><header><b>HONORABLE</b><span>Settings</span></header><section class="intro"><h1>Simple by design.</h1><p>Privacy, plans, appearance, and legal.</p></section><div class="settings"><div><b>Photo access</b><span>Managed by device ›</span></div><div><b>Usage</b><span>Plan and limits ›</span></div><div><b>Plans</b><span>Compare options ›</span></div><div><b>About & legal</b><span>Terms & privacy ›</span></div><div><b>Engine health</b><span>Developer diagnostics ›</span></div></div>${nav('Settings')}</main>`}
function storage(){return `<main class="phone legacy legacy-storage mono"><div class="legacy-brand"><b>h</b><span><strong>Honorable</strong><small>Local library</small></span><em>●&nbsp; On device</em></div><section class="bubble-storage-intro"><small>LOCAL LIBRARY</small><h1>Your library<br><em>stays local.</em></h1><p>See what is ready to search and manage<br>Honorable’s private index.</p></section><section class="bubble-index"><div class="bubble-ring"><b>100<small>%</small></b></div><div><small>SEARCH INDEX</small><b>12,540 ready</b><span>Indexing complete</span></div><i>✓</i></section><div class="bubble-storage-grid"><div><small>INDEXED MEDIA</small><b>12,540</b><span>Ready to search</span></div><div><small>STATUS</small><b>Ready</b><span>Indexing complete</span></div><div><small>INDEX STORAGE</small><b>On device</b><span>Private database</span></div><div><small>PHOTO ACCESS</small><b>Selected</b><span>Managed by device</span></div></div><div class="bubble-storage-actions"><button><i>↻</i><span><b>Reindex library</b><small>Rebuild Honorable’s search index only</small></span><em>›</em></button><button><i>◉</i><span><b>Manage photo access</b><small>Choose photos and videos</small></span><em>›</em></button></div><div class="bubble-storage-safe"><i>✓</i><span><b>Your originals stay safe</b><small>Honorable never deletes photos or videos.</small></span><em>Cache not measured</em></div>${legacyDock('Storage')}</main>`}
function memories(){return `<main class="phone hybrid memories-screen"><header><b>MEMORIES</b><span>All dates</span></header>${search()}<div class="filters library-filters"><b>All</b><span>Photos</span><span>Videos</span><span>Date</span></div><div class="date-head"><b>Today</b><span>9 moments</span></div><div class="grid memories-grid">${media}</div><div class="date-head second-date"><b>August 29</b><span>Earlier</span></div><div class="grid memories-grid lower">${media}</div>${nav('Memories')}</main>`}
function searchMode(){return `<main class="phone hybrid sheet-preview"><header><b>HONORABLE</b><span>On-device</span></header><section class="intro home-intro"><em>PRIVATE PHOTO SEARCH</em><h1>Find a moment.</h1><p>Describe anything you remember.</p></section>${search()}<button class="mode">⌕ &nbsp; Quick <i>⌄</i></button><div class="result-head home-recent"><b>Recent</b><span>Your library</span></div><div class="grid home-grid">${media}</div>${nav()}<div class="sheet-scrim"></div><section class="mode-sheet"><i class="sheet-handle"></i><div class="sheet-title"><span><b>Search mode</b><small>Choose how Honorable searches this device.</small></span><em>×</em></div><div class="mode-row selected"><span><b>Quick</b><small>Fast and lightweight</small></span><strong>✓</strong></div><div class="mode-row locked"><span><b>Smart</b><small>Better understanding of what you remember</small></span><strong>⌑ Upgrade</strong></div><div class="mode-row locked"><span><b>Deep Search</b><small>Most detailed local search</small></span><strong>⌑ Pro</strong></div><p>Availability follows your verified plan. Every mode runs locally; free search is never intentionally slowed.</p></section></main>`}
function legal(){return `<main class="phone hybrid legal"><header><b>‹</b><span></span></header><section class="intro"><h1>About & legal</h1><p>Honorable keeps search and indexing on your device.</p></section><div class="settings legal-list"><div><b>Terms of Service</b><span>›</span></div><div><b>Privacy Policy</b><span>›</span></div></div><div class="legal-note"><b>No legal tab.</b><span>Legal information lives in Settings, outside primary navigation.</span></div></main>`}
const legacyDock=active=>`<nav class="legacy-dock">${[['⌂','Home'],['◎','Memories'],['◫','Storage'],['⚙','Settings']].map(x=>`<span class="${x[1]===active?'active':''}"><i>${x[0]}</i><small>${x[1]}</small></span>`).join('')}</nav>`;
function legacyHome(){return `<main class="phone legacy mono"><div class="legacy-brand"><b>h</b><span><strong>Honorable</strong><small>Private intelligence</small></span><em>●&nbsp; On device</em></div><section class="legacy-hero"><div class="legacy-bubbles"><i></i><i></i><i></i><i></i></div><small>● &nbsp; YOUR LIFE, SEARCHABLE</small><h1>Find what<br><em>matters.</em></h1><p>Describe a moment the way you remember it.<br>Honorable finds it privately, right here.</p><div class="legacy-search"><i>✦</i><span><small>Ask your memories</small><b>A white beach with tall grass</b></span><em>↗</em></div></section><div class="legacy-bento"><div><i>◎</i><span><b>Memories</b><small>Find any moment</small></span><em>↗</em></div><div><i>◫</i><span><b>Storage</b><small>Manage local index</small></span><em>↗</em></div></div><div class="legacy-private"><i>⌁</i><span><b>Yours stays yours</b><small>Search and media never leave this phone.</small></span><em>✓</em></div>${legacyDock('Home')}</main>`}
function legacyMemories(){return `<main class="phone legacy legacy-memories mono"><div class="legacy-memory-ambient"><i></i><i></i></div><div class="legacy-brand"><b>h</b><span><strong>Honorable</strong><small>Memory space</small></span><em>●&nbsp; On device</em></div><section class="legacy-memory-intro"><small>PRIVATE MEMORY SEARCH</small><h1>What do you<br><em>remember?</em></h1><p>A color, a place, a tiny detail—start anywhere.</p></section><div class="legacy-memory-search">⌕ <span>Start describing…</span><b>↗</b></div><div class="legacy-section-title"><b>Start anywhere</b><small>Made for your library</small></div><div class="legacy-prompt feature beach"><i>⌕</i><span><small>TRY A SCENE</small><b>White beach<br>with tall grass</b><em>Place + texture + color</em></span></div><div class="legacy-prompt-row"><div class="legacy-prompt car"><i>◒</i><span><small>COLOR + WEATHER</small><b>Red car<br>in snow</b></span></div><div class="legacy-prompt cake"><i>✦</i><span><small>OBJECT + LIGHT</small><b>Birthday cake<br>by a window</b></span></div></div><div class="legacy-local"><i>✓</i><span><b>Private by default</b><small>Photos and searches stay on this device.</small></span><em>9,812 ready</em></div>${legacyDock('Memories')}</main>`}
const selected={klass:'mono',eyebrow:'PRIVATE PHOTO SEARCH',title:'Find a moment.',sub:'Describe anything you remember.'};
const screens={'01-home':legacyHome,'02-memories':legacyMemories,'03-storage':storage};
document.body.innerHTML=(screens[id]||screens['01-home'])();
