import React from 'react';
import {FlatList,Image,ImageSourcePropType,Pressable,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {colors,grid} from '../design-system/tokens';
import type {SearchResult} from '../native/HonorableNative';
export type MediaItem={id:string;source?:ImageSourcePropType;uri?:string;type:'IMAGE'|'VIDEO';duration?:string;cropIndex?:number;result?:SearchResult};
const sheet=require('../assets/demo-media/honorable-preview-contact-sheet.png');
export const previewMedia:MediaItem[]=['dog','birthday','car','receipt','tennis','food','lake','verification','concert'].map((id,index)=>({id,source:sheet,type:index===8?'VIDEO':'IMAGE',duration:index===8?'2:14':undefined,cropIndex:index}));
function Tile({item,size,onPress}:{item:MediaItem;size:number;onPress:(item:MediaItem)=>void}){const crop=item.cropIndex;return <Pressable accessibilityRole="imagebutton" accessibilityLabel={`${item.type.toLowerCase()} result`} onPress={()=>onPress(item)} style={[styles.tile,{width:size,height:size}]}>{crop===undefined?<Image source={item.source??{uri:item.uri}} style={styles.fill}/>:<Image source={item.source} resizeMode="stretch" style={{position:'absolute',width:size*3,height:size*3,left:-(crop%3)*size,top:-Math.floor(crop/3)*size}}/>}{item.type==='VIDEO'&&<View style={styles.video}><Text style={styles.videoText}>▶ {item.duration??'video'}</Text></View>}</Pressable>}
export function MediaGrid({items,onPress}:{items:MediaItem[];onPress:(item:MediaItem)=>void}){const{width}=useWindowDimensions();const size=(width-grid.gap*2)/3;return <FlatList accessibilityLabel="Media results" data={items} keyExtractor={item=>item.id} numColumns={3} scrollEnabled={false} columnWrapperStyle={styles.row} renderItem={({item})=><Tile item={item} size={size} onPress={onPress}/>}/>}
const styles=StyleSheet.create({row:{gap:grid.gap,marginBottom:grid.gap},tile:{backgroundColor:colors.surface,overflow:'hidden'},fill:{width:'100%',height:'100%',resizeMode:'cover'},video:{position:'absolute',right:7,bottom:7,paddingHorizontal:7,paddingVertical:4,borderRadius:8,backgroundColor:'rgba(0,0,0,.68)'},videoText:{color:'#fff',fontSize:10,fontWeight:'700'}});
