import React from'react';
import{Modal,Pressable,StyleSheet,View}from'react-native';
import{Check,ChevronDown,Lock,Search as SearchIcon,X}from'lucide-react-native';
import{Text}from'@/components/ui/text';
import{colors}from'../design-system/tokens';
import{isSearchModeAvailable,searchModes,SearchModeId}from'../search/searchModes';
import type{EntitlementState}from'../native/HonorableNative';

export function SearchModeControl({value,onPress}:{value:SearchModeId;onPress:()=>void}){const mode=searchModes.find(item=>item.id===value)!;return <Pressable accessibilityRole="button" accessibilityLabel={`Search mode: ${mode.name}`} onPress={onPress} style={styles.control}><SearchIcon color={colors.iconMuted} size={13}/><Text className="text-[12px] font-semibold">{mode.name}</Text><ChevronDown color={colors.iconMuted} size={13}/></Pressable>}
export function SearchModeSheet({visible,value,entitlement,onClose,onSelect}:{visible:boolean;value:SearchModeId;entitlement?:EntitlementState;onClose:()=>void;onSelect:(mode:SearchModeId)=>void}){return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.scrim} onPress={onClose}/><View style={styles.sheet}><View style={styles.handle}/><View style={styles.sheetHeader}><View><Text className="text-[20px] font-semibold">Search mode</Text><Text variant="muted" className="mt-1">Choose how Honorable searches this device.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close search modes" onPress={onClose} style={styles.close}><X color={colors.icon} size={18}/></Pressable></View>{searchModes.map(mode=>{const available=isSearchModeAvailable(mode,entitlement);const selected=mode.id===value;return <Pressable key={mode.id} accessibilityRole="radio" accessibilityState={{checked:selected,disabled:!available}} onPress={()=>{if(available){onSelect(mode.id);onClose();}}} style={[styles.mode,selected&&styles.selected,!available&&styles.locked]}><View style={styles.modeCopy}><Text className="font-semibold">{mode.name}</Text><Text variant="muted" className="mt-1 text-[13px]">{mode.description}</Text></View>{selected?<Check color={colors.selection} size={20}/>:available?null:<View style={styles.requirement}><Lock color={colors.iconMuted} size={12}/><Text variant="muted" className="text-[11px] font-semibold">{mode.requirementLabel}</Text></View>}</Pressable>})}<Text variant="muted" className="mt-3 text-[12px] leading-5">Availability follows your verified plan. Every mode runs locally; free search is never intentionally slowed.</Text></View></Modal>}
const styles=StyleSheet.create({control:{alignSelf:'flex-start',marginHorizontal:16,marginTop:10,flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:11,paddingVertical:7,borderRadius:999,backgroundColor:colors.surface},scrim:{...StyleSheet.absoluteFill,backgroundColor:colors.scrim},sheet:{position:'absolute',left:0,right:0,bottom:0,paddingHorizontal:18,paddingTop:10,paddingBottom:34,borderTopLeftRadius:28,borderTopRightRadius:28,backgroundColor:colors.surfaceRaised},handle:{alignSelf:'center',width:38,height:4,borderRadius:2,backgroundColor:colors.separator},sheetHeader:{marginTop:18,marginBottom:14,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},close:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface},mode:{minHeight:72,marginTop:8,paddingHorizontal:15,paddingVertical:13,borderRadius:18,borderWidth:1,borderColor:colors.separator,flexDirection:'row',alignItems:'center'},selected:{borderColor:'rgba(117,167,255,.48)',backgroundColor:colors.active},locked:{opacity:.72},modeCopy:{flex:1,paddingRight:12},requirement:{flexDirection:'row',alignItems:'center',gap:5,paddingHorizontal:9,paddingVertical:6,borderRadius:999,backgroundColor:colors.surface}});
