import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from'react';
import type{MemoryAccount}from'./MemoryPassClient';import type{PassId,SeranCreditModel}from'./catalog';
import{honorableNative}from'../native/HonorableNative';
type Value={account?:MemoryAccount;status:string;connected:boolean;signedIn:boolean;loading:boolean;error?:string;googleConfigured:boolean;signInGoogle:()=>Promise<void>;signInDev:(email:string)=>Promise<void>;signOut:()=>Promise<void>;refresh:()=>Promise<void>;buy:(id:PassId)=>Promise<void>;restore:()=>Promise<void>;startSearch:(model:SeranCreditModel,requestId:string)=>Promise<void>;finishSearch:(requestId:string,outcome:string)=>Promise<void>;charge:(model:SeranCreditModel,requestId:string)=>Promise<void>};
const Context=createContext<Value|undefined>(undefined);
export function MemoryPassProvider({children}:{children:React.ReactNode}){
 const[account,setAccount]=useState<MemoryAccount>();const[status,setStatus]=useState('restoring');const[loading,setLoading]=useState(false);const[error,setError]=useState<string>();const[googleConfigured,setGoogleConfigured]=useState(false);
 const apply=useCallback((value:{status:string;account?:MemoryAccount})=>{setAccount(value.account);setStatus(value.status);setError(undefined)},[]);
 const refresh=useCallback(async()=>{try{apply(await honorableNative.restoreAccountSession())}catch{setStatus('unavailable');setError('Connect to the internet to restore your account.')}},[apply]);
 useEffect(()=>{honorableNative.getAccountConfiguration().then(config=>setGoogleConfigured(config.googleConfigured&&!!config.apiUrl)).catch(()=>undefined);void refresh()},[refresh]);
 const signInGoogle=useCallback(async()=>{setLoading(true);setStatus('signing-in');try{apply(await honorableNative.signInAccountWithGoogle())}catch{setStatus('welcome');setError('Sign-in was not completed. Please try again.')}finally{setLoading(false)}},[apply]);
 const signOut=useCallback(async()=>{setAccount(undefined);setStatus('restoring');setError(undefined);try{await honorableNative.signOutAccountSession();setStatus('welcome')}catch{setStatus('unavailable');setError('Unable to clear the secure session. Please retry.')}},[]);
 const run=useCallback(async(route:string,body:object)=>{if(status!=='online')throw Error('Reconnect to verify your account first.');setLoading(true);try{const next=await honorableNative.accountSessionAction(route,JSON.stringify(body));setAccount(next);setError(undefined)}catch(reason){await refresh();throw reason}finally{setLoading(false)}},[status,refresh]);
 const value=useMemo<Value>(()=>({account,status,connected:status==='online',signedIn:status==='online'||status==='offline',loading,error,googleConfigured,signInGoogle,signInDev:async()=>{throw Error('Development sign-in is only available in the web test tools.')},signOut,refresh,buy:async()=>{throw Error('Purchases are not enabled in this app.')},restore:()=>run('/v1/purchases/restore',{}),startSearch:async(model,requestId)=>{await honorableNative.accountSessionAction('/v1/search/start',JSON.stringify({model,requestId}))},finishSearch:(requestId,outcome)=>run('/v1/search/complete',{requestId,outcome}),charge:(model,requestId)=>run('/v1/credits/deduct',{model,requestId})}),[account,status,loading,error,googleConfigured,signInGoogle,signOut,refresh,run]);
 return <Context.Provider value={value}>{children}</Context.Provider>
}
export function useMemoryPass(){const value=useContext(Context);if(!value)throw new Error('useMemoryPass must be used inside MemoryPassProvider');return value}
