const { chromium } = require('../../Honorable-mobile-app-main/ui-previews/node_modules/playwright');
const path = require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1400,height:1150},deviceScaleFactor:2});
 await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
 const reader=page.frameLocator('#reader');
 await reader.locator('mark').first().waitFor();
 await page.screenshot({path:path.join(__dirname,'automatic-highlights.png'),fullPage:true});
 await reader.locator('mark[data-novel-companion="character"]').first().click();
 await reader.getByRole('dialog').waitFor();
 await reader.getByRole('dialog',{name:'Elizabeth Bennet information',exact:true}).waitFor();
 await reader.locator('.role-tags').getByText('MC · Main Character',{exact:true}).waitFor();
 await page.locator('#reader').screenshot({path:path.join(__dirname,'character-information.png')});
 await page.locator('#reader').screenshot({path:path.join(__dirname,'character-profile-corrected.png')});
 await page.locator('#reader').screenshot({path:path.join(__dirname,'character-profile-square.png')});
 await page.locator('#reader').screenshot({path:path.join(__dirname,'character-profile-large-square.png')});
 await reader.getByText('Power scale · Current chapter',{exact:true}).scrollIntoViewIfNeeded();
 await page.locator('#reader').screenshot({path:path.join(__dirname,'character-power-stats.png')});
 await page.keyboard.press('Escape');
 await reader.locator('mark[data-novel-companion="place"]').click();
 await page.locator('#reader').screenshot({path:path.join(__dirname,'place-information.png')});
 await page.keyboard.press('Escape');
 await reader.getByRole('button',{name:'Show current chapter summary',exact:true}).click();
 await reader.getByRole('dialog').waitFor();
 await page.locator('#reader').screenshot({path:path.join(__dirname,'chapter-summary.png')});
 await browser.close();console.log('Updated automatic reading overview and sidebar screenshots.');
})().catch(error=>{console.error(error);process.exit(1);});
