'use strict';
const {catalog}=require('../ledger');
const DAY=86400000;
const pct=(n,d)=>d?Math.round(n/d*1000)/10:null;
const sum=(rows,fn)=>rows.reduce((n,r)=>n+(fn(r)||0),0);
const quantile=(values,p)=>{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.max(0,Math.ceil(sorted.length*p)-1))]};
function environments(data,defaultEnvironment){
 const developmentIds=new Set(Object.entries(data.identities||{}).filter(([provider])=>provider.startsWith('DEVELOPMENT:')).map(([,id])=>id));
 return id=>developmentIds.has(id)?'development':data.accounts[id]?.environment||'unknown';
}
function accountRows(ledger,environment){const env=environments(ledger.data);return Object.entries(ledger.data.accounts).filter(([id])=>env(id)===environment).map(([id,a])=>({id,...a}));}
function dateStart(range,now){return range==='all'?0:now-({'24h':1,'7d':7,'30d':30,'90d':90}[range]||30)*DAY;}
function balance(ledger,a){const cycle=ledger.cycle().key,pool=ledger.data.installations?.[a.installation]?.cycles?.[cycle];return{purchased:a.balance||0,free:pool?.owner===a.id?pool.remaining:0};}
function safeUser(ledger,a,analytics,{pii=false}={}){
 const events=analytics.events.filter(e=>e.accountId===a.id),searches=Object.values(ledger.data.searches||{}).filter(s=>s.accountId===a.id);
 const last=events.filter(e=>!['api_request','error_occurred'].includes(e.type)).sort((a,b)=>b.at.localeCompare(a.at))[0];
 return{id:a.id,...(pii?{email:a.profile?.email||null}:{}),registeredAt:a.createdAt||null,lastActivity:last?.at||null,platform:last?.metadata.platform||'UNKNOWN',appVersion:last?.metadata.appVersion||null,credits:balance(ledger,a),subscription:{status:a.subscription?.status||'NONE',test:!!a.subscription?.test},purchases:(a.purchases||[]).map(p=>({passId:p.passId,credits:p.credits,test:p.test!==false})),searches:searches.length,successfulSearches:searches.filter(s=>s.state==='SUCCESS').length,ledger:(a.transactions||[]).slice(-30).reverse().map(t=>({id:t.id,type:t.type,credits:t.credits,freeSpent:t.freeSpent??null,purchasedSpent:t.purchasedSpent??null,passId:t.passId??null,model:t.model??null,at:t.createdAt}))};
}
function buildMetrics({ledger,analytics,environment,range='30d',clock=Date.now}){
 const now=clock(),from=dateStart(range,now),state=analytics.snapshot(),accounts=accountRows(ledger,environment),ids=new Set(accounts.map(a=>a.id));
 const dayKey=new Date(now).toISOString().slice(0,10),monthKey=dayKey.slice(0,7),dayStart=Date.parse(dayKey),weekStart=dayStart-((new Date(now).getUTCDay()+6)%7)*DAY;
 const events=state.events.filter(e=>e.environment===environment&&Date.parse(e.at)>=from);
 const days=Object.values(state.days).filter(d=>d.environment===environment);
 const activeSince=(start)=>new Set(days.filter(d=>Date.parse(d.date)+DAY>start).flatMap(d=>d.active.filter(id=>ids.has(id)&&(Date.parse(d.date)>=start||Date.parse(d.lastActive?.[id]||'')>=start||state.events.some(e=>e.accountId===id&&e.environment===environment&&Date.parse(e.at)>=start&&e.at.startsWith(d.date)&&['session_started','session_active','search_started','result_opened','editor_opened','edit_saved','edit_tool_used','workspace_opened'].includes(e.type))))));
 const uniqueEvent=(name,start=from)=>new Set(days.filter(d=>Date.parse(d.date)+DAY>start).flatMap(d=>d.usersByEvent[name]||[]));
 const active=activeSince(from),dau=activeSince(dayStart),wau=activeSince(now-7*DAY),mau=activeSince(now-30*DAY);
 const activeDays=new Map();for(const day of days)for(const id of day.active)activeDays.set(id,(activeDays.get(id)||0)+1);
 const transactions=accounts.flatMap(a=>(a.transactions||[]).map(t=>({...t,accountId:a.id})));
 const tx=transactions.filter(t=>Date.parse(t.createdAt)>=from);
 const debits=tx.filter(t=>t.type==='DEBIT'),passTx=tx.filter(t=>t.type==='MEMORY_PASS_GRANT');
 const allPasses=accounts.flatMap(a=>(a.purchases||[]).map(p=>({...p,accountId:a.id})));
 const jobs=Object.values(ledger.data.searches||{}).filter(s=>ids.has(s.accountId));
 const searches=jobs.filter(s=>s.createdAt&&Date.parse(s.createdAt)>=from);
 const durations=searches.filter(s=>s.durationMs!=null&&s.state!=='PENDING').map(s=>s.durationMs);
 const success=searches.filter(s=>s.state==='SUCCESS'),failed=searches.filter(s=>s.state==='FAILED'),cancelled=searches.filter(s=>s.state==='CANCELLED');
 const passUsers=new Set(allPasses.map(p=>p.accountId)),studioUsers=new Set(accounts.filter(a=>a.subscription?.status==='ACTIVE').map(a=>a.id));
 const registrations=accounts.filter(a=>a.createdAt),within=(start)=>registrations.filter(a=>Date.parse(a.createdAt)>=start).length;
 const segmentNames=['FREE','MEMORY PASS','STUDIO','STUDIO + MEMORY PASS'];
 const segment=(a)=>studioUsers.has(a.id)?passUsers.has(a.id)?3:2:passUsers.has(a.id)?1:0;
 const segments=segmentNames.map((name,i)=>{const members=accounts.filter(a=>segment(a)===i);const eligible=members.filter(a=>a.createdAt&&Date.parse(a.createdAt)>=Date.parse(state.startedAt)&&Date.parse(a.createdAt)<now-8*DAY&&Date.parse(a.createdAt)+7*DAY>=now-analytics.aggregateDays*DAY),returned=eligible.filter(a=>days.some(d=>d.date===new Date(Date.parse(a.createdAt)+7*DAY).toISOString().slice(0,10)&&d.active.includes(a.id)));return{name,count:members.length,percentage:pct(members.length,accounts.length),active:members.filter(a=>active.has(a.id)).length,retention:pct(returned.length,eligible.length)}});
 const floorDate=(d,unit)=>{const date=new Date(d);if(unit==='month')return date.toISOString().slice(0,7);if(unit==='week')date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));return date.toISOString().slice(0,10)};
 const growth=(unit)=>{const grouped={};for(const a of registrations){if(Date.parse(a.createdAt)<from)continue;const key=floorDate(a.createdAt,unit);grouped[key]??={period:key,registrations:0,active:new Set(),returning:new Set()};grouped[key].registrations++}for(const d of days){if(Date.parse(d.date)+DAY<=from)continue;const key=floorDate(d.date,unit);grouped[key]??={period:key,registrations:0,active:new Set(),returning:new Set()};for(const id of d.active){grouped[key].active.add(id);if(days.some(earlier=>earlier.date<d.date&&earlier.active.includes(id)))grouped[key].returning.add(id)}}let cumulative=registrations.filter(a=>Date.parse(a.createdAt)<from).length;return Object.values(grouped).sort((a,b)=>a.period.localeCompare(b.period)).map(g=>{cumulative+=g.registrations;return{period:g.period,registrations:g.registrations,cumulativeKnown:cumulative,active:g.active.size,returning:g.returning.size}})};
 const freeTx=transactions.filter(t=>['FREE_MONTHLY_GRANT','FREE_MONTHLY_RESET'].includes(t.type)&&t.createdAt.startsWith(monthKey));
 const freeUsed=transactions.filter(t=>t.type==='DEBIT'&&t.createdAt.startsWith(monthKey));
 const recipients=new Set(freeTx.map(t=>t.accountId));
 const spentBy=id=>sum(freeUsed.filter(t=>t.accountId===id),t=>t.freeSpent);
 const exhausted=new Set([...recipients].filter(id=>spentBy(id)>=ledger.freeMonthly));
 const afterFree=accounts.filter(a=>{const firstPass=(a.transactions||[]).find(t=>t.type==='MEMORY_PASS_GRANT');return firstPass&&(a.transactions||[]).some(t=>t.type==='DEBIT'&&(t.freeSpent||0)>0&&t.createdAt<firstPass.createdAt)});
 const afterExhaustion=accounts.filter(a=>{let used=0;return(a.transactions||[]).filter(t=>t.createdAt.startsWith(monthKey)).some(t=>{if(t.type==='DEBIT')used+=t.freeSpent||0;return t.type==='MEMORY_PASS_GRANT'&&used>=ledger.freeMonthly})});
 const passTiers=catalog.passes.map(p=>{const purchases=passTx.filter(t=>t.passId===p.id);return{id:p.id,credits:p.credits,purchases:purchases.length,creditsSold:sum(purchases,t=>t.credits),testPurchases:purchases.filter(t=>t.test===true||environment==='development').length,unclassifiedPurchases:purchases.filter(t=>t.test!==true&&environment!=='development').length,revenue:null}});
 const eventRows=(types,key)=>{const map={};for(const e of events.filter(e=>types.includes(e.type))){const name=e.metadata[key]||e.type;map[name]=(map[name]||0)+1}return Object.entries(map).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count)};
 const retention=(offset)=>{const earliest=Date.parse(state.startedAt);const eligible=registrations.filter(a=>{const t=Date.parse(a.createdAt);return t>=earliest&&t<now-(offset+1)*DAY&&t+offset*DAY>=now-analytics.aggregateDays*DAY});const returned=eligible.filter(a=>{const target=new Date(Date.parse(a.createdAt)+offset*DAY).toISOString().slice(0,10);return days.some(d=>d.date===target&&d.active.includes(a.id))});return{day:offset,eligible:eligible.length,returned:returned.length,percentage:pct(returned.length,eligible.length)}};
 const cohorts=(unit)=>[...new Set(registrations.map(a=>floorDate(a.createdAt,unit)))].sort().map(period=>{const members=registrations.filter(a=>floorDate(a.createdAt,unit)===period);return{period,registered:members.length,active:members.filter(a=>active.has(a.id)).length,observedReturning:members.filter(a=>(activeDays.get(a.id)||0)>1).length}});
 const funnelStages=[['REGISTERED',new Set(accounts.map(a=>a.id))],['AUTHENTICATED',new Set([...uniqueEvent('session_started',0),...uniqueEvent('session_active',0)])],['FIRST SEARCH',new Set(jobs.map(s=>s.accountId))],['SEARCH SUCCESS',new Set(jobs.filter(s=>s.state==='SUCCESS').map(s=>s.accountId))],['RESULT OPEN',uniqueEvent('result_opened',0)],['EDIT OPEN',uniqueEvent('editor_opened',0)],['SAVE COPY',uniqueEvent('edit_saved',0)],['MEMORY PASS PURCHASE',passUsers],['STUDIO SUBSCRIPTION',studioUsers]];
 let prior=null;const funnel=funnelStages.map(([stage,set])=>{const observed=[...set].filter(id=>ids.has(id));const count=observed.length;const converted=prior?observed.filter(id=>prior.has(id)).length:count;const row={stage,observedUsers:count,fromPreviousObserved:pct(converted,prior?.size??count),ofRegistered:pct(count,accounts.length)};prior=new Set(observed);return row});
 const versions={};for(const e of events){const platform=e.metadata.platform||'UNKNOWN',version=e.metadata.appVersion||'UNKNOWN',build=e.metadata.buildNumber||'UNKNOWN',key=platform+':'+version+':'+build;const row=versions[key]??={platform,version,build,users:new Set(),active:new Set(),searches:0,errors:0,latencies:[],crashes:null};if(e.accountId)row.users.add(e.accountId);if(e.accountId&&active.has(e.accountId))row.active.add(e.accountId);if(e.type==='search_started')row.searches++;if(['client_error','error_occurred'].includes(e.type))row.errors++;if(e.type==='search_completed'&&e.metadata.durationMs!=null)row.latencies.push(e.metadata.durationMs);}
 const errors={};for(const e of events.filter(e=>['client_error','error_occurred'].includes(e.type))){const key=[e.metadata.errorCode,e.metadata.platform||'UNKNOWN',e.metadata.appVersion||'UNKNOWN',e.at.slice(0,10)].join('|');errors[key]??={type:e.metadata.errorCode,platform:e.metadata.platform||'UNKNOWN',version:e.metadata.appVersion||'UNKNOWN',date:e.at.slice(0,10),count:0};errors[key].count++;}
 const api=events.filter(e=>e.type==='api_request'),apiTimes=api.map(e=>e.metadata.durationMs).filter(Number.isFinite);
 const reconciliation=jobs.filter(j=>(j.state==='SUCCESS')!==!!ledger.data.deductions[Object.entries(ledger.data.searches).find(([,v])=>v===j)?.[0]]).length;
 return {
  environment,range,generatedAt:new Date(now).toISOString(),coverage:{startedAt:state.startedAt,rawDays:analytics.rawDays,aggregateDays:analytics.aggregateDays,historicalRegistrationsUnknown:accounts.length-registrations.length,historicalSearchTimesUnknown:jobs.filter(s=>!s.createdAt).length,unknownEnvironmentAccounts:Object.keys(ledger.data.accounts).length-Object.keys(ledger.data.accounts).filter(id=>['development','staging','production'].includes(environments(ledger.data)(id))).length,analyticsAvailable:analytics.available},
  overview:{totalUsers:accounts.length,newToday:within(dayStart),newWeek:within(weekStart),newMonth:within(Date.parse(monthKey+'-01')),dau:dau.size,wau:wau.size,mau:mau.size,returning:[...active].filter(id=>(activeDays.get(id)||0)>1).length,studioMembers:studioUsers.size,passUsers:passUsers.size,freeOnly:segments[0].count},
  growth:{daily:growth('day'),weekly:growth('week'),monthly:growth('month')},segments,
  passes:{totalPurchases:allPasses.length,purchasesInRange:passTx.length,today:transactions.filter(t=>t.type==='MEMORY_PASS_GRANT'&&Date.parse(t.createdAt)>=dayStart).length,week:transactions.filter(t=>t.type==='MEMORY_PASS_GRANT'&&Date.parse(t.createdAt)>=weekStart).length,month:transactions.filter(t=>t.type==='MEMORY_PASS_GRANT'&&t.createdAt.startsWith(monthKey)).length,creditsPurchased:sum(passTx,t=>t.credits),purchasedCreditsConsumed:sum(debits,t=>t.purchasedSpent??-t.credits),purchasedCreditsRemaining:sum(accounts,a=>a.balance),averageCreditsPerPurchaser:passUsers.size?sum(allPasses,p=>p.credits)/passUsers.size:null,repeatPurchasers:accounts.filter(a=>(a.purchases?.length||0)>1).length,firstPassConversion:pct(passUsers.size,accounts.length),afterFreeUse:afterFree.length,tiers:passTiers,realRevenue:null,revenueStatus:'Real billing is not connected. Test/unknown grants are not revenue.'},
  free:{month:monthKey,granted:sum(freeTx,t=>t.credits),used:sum(freeUsed,t=>t.freeSpent),averageUsedPerRecipient:recipients.size?sum(freeUsed,t=>t.freeSpent)/recipients.size:null,exhausted:exhausted.size,usedNone:[...recipients].filter(id=>spentBy(id)===0).length,convertedAfterExhaustion:afterExhaustion.length,installationConflicts:ledger.data.analyticsCounters?.[environment]?.installationConflicts??null,accountSwitchBlocks:ledger.data.analyticsCounters?.[environment]?.accountSwitchBlocks??null},
  search:{requests:searches.length,successful:success.length,failed:failed.length,cancelled:cancelled.length,pending:searches.filter(s=>s.state==='PENDING').length,completionRate:pct(success.length,searches.length),perActiveUser:active.size?searches.length/active.size:null,averageLatencyMs:durations.length?sum(durations,x=>x)/durations.length:null,p50LatencyMs:quantile(durations,.5),p95LatencyMs:quantile(durations,.95),latencyDefinition:'Trusted engine latency when supplied by the verifier; otherwise server transaction duration. No client-supplied timing is trusted.',daily:growth('day').map(d=>({date:d.period,requests:searches.filter(s=>s.createdAt.startsWith(d.period)).length})),verifierFailures:events.filter(e=>e.metadata.errorCode==='COMPLETION_REJECTED').length,reconciliationErrors:reconciliation,indexRequests:null},
  models:catalog.models.map(m=>{const rows=searches.filter(s=>s.model===m.model),times=rows.map(s=>s.durationMs).filter(Number.isFinite);return{name:m.name,model:m.model,available:m.available,requests:rows.length,successful:rows.filter(s=>s.state==='SUCCESS').length,failed:rows.filter(s=>s.state==='FAILED').length,share:pct(rows.length,searches.length),averageLatencyMs:times.length?sum(times,x=>x)/times.length:null,creditsConsumed:-sum(debits.filter(t=>t.model===m.model),t=>t.credits)}}),
  media:{photoSearches:events.some(e=>e.type==='search_completed'&&e.metadata.mediaType)?events.filter(e=>e.type==='search_completed'&&e.metadata.mediaType==='IMAGE').length:null,videoSearches:events.some(e=>e.type==='search_completed'&&e.metadata.mediaType)?events.filter(e=>e.type==='search_completed'&&e.metadata.mediaType==='VIDEO').length:null,videoMoments:events.some(e=>e.type==='search_completed'&&e.metadata.mediaType)?events.filter(e=>e.type==='search_completed'&&e.metadata.videoMoment).length:null,photoOpens:events.filter(e=>e.type==='result_opened'&&e.metadata.mediaType==='IMAGE').length,videoOpens:events.filter(e=>e.type==='result_opened'&&e.metadata.mediaType==='VIDEO').length,searchToEdit:events.filter(e=>e.type==='editor_opened'&&e.metadata.fromSearch).length,note:'Result-type split exists only for trusted typed completions. UI opens are client-reported.'},
  editor:{opened:events.filter(e=>e.type==='editor_opened').length,saved:events.filter(e=>e.type==='edit_saved').length,tools:eventRows(['edit_tool_used'],'tool'),workspaces:eventRows(['workspace_opened'],'workspace'),note:'Client-reported interaction telemetry; no media or code collected.'},
  studio:{active:studioUsers.size,activeProduction:accounts.filter(a=>a.subscription?.status==='ACTIVE'&&!a.subscription?.test).length,testEntitlements:accounts.filter(a=>a.subscription?.status==='ACTIVE'&&a.subscription?.test).length,expired:accounts.filter(a=>a.subscription?.status==='EXPIRED').length,newSubscriptions:tx.filter(t=>t.type==='STUDIO_ENTITLEMENT_START').length,cancellations:tx.filter(t=>t.type==='STUDIO_ENTITLEMENT_END').length,featureInterest:eventRows(['feature_interest'],'feature'),revenue:null},
  retention:{days:[retention(1),retention(7),retention(30)],weekly:cohorts('week'),monthly:cohorts('month'),inactive:accounts.filter(a=>!active.has(a.id)).length,neverSearched:accounts.filter(a=>!jobs.some(j=>j.accountId===a.id)).length,searchedOnce:accounts.filter(a=>jobs.filter(j=>j.accountId===a.id).length===1).length,repeatedSearch:accounts.filter(a=>jobs.filter(j=>j.accountId===a.id).length>1).length,note:'Exact calendar-day return; only cohorts observed since collection began are eligible. No eligible history means unavailable.'},funnel,
  platforms:Object.entries(days.filter(d=>Date.parse(d.date)+DAY>from).reduce((map,d)=>{for(const[p,list]of Object.entries(d.platforms||{})){map[p]??=new Set();list.forEach(id=>map[p].add(id))}return map},{})).map(([platform,set])=>({platform,activeUsers:set.size})),
  versions:Object.values(versions).map(v=>({...v,users:v.users.size,active:v.active.size,averageLatencyMs:v.latencies.length?sum(v.latencies,x=>x)/v.latencies.length:null,latencies:undefined,outdated:null})),errors:Object.values(errors),
  live:events.filter(e=>e.type!=='api_request'&&e.type!=='session_active').slice(-50).reverse().map(e=>({at:e.at,event:e.type,account:e.accountId?e.accountId.slice(0,8):null,authority:e.authority,...e.metadata})),
  health:{accountApi:'UP',database:'IN_MEMORY_LEDGER_LOADED',analytics:analytics.available?'UP':'UNAVAILABLE',droppedEvents:analytics.dropped,averageApiLatencyMs:apiTimes.length?sum(apiTimes,x=>x)/apiTimes.length:null,apiErrorRate:pct(api.filter(e=>e.metadata.failed).length,api.length),serverMode:environment,searchService:'NOT PROBED',webAdapter:'NOT PROBED',recentDeployment:process.env.HONORABLE_DEPLOYMENT_ID?.match(/^[a-zA-Z0-9._-]{1,64}$/)?.[0]||null,crashTelemetry:'NOT INTEGRATED'},
 };
}
module.exports={buildMetrics,accountRows,safeUser,environments};
