// Generated by scripts/generate-design.cjs from product/design-tokens.json.
const semantic={"canvas":"#000000","surface":"#080808","surfaceRaised":"#101010","surfaceSelected":"#171717","border":"#242424","textPrimary":"#FFFFFF","textSecondary":"#B8B8B8","textTertiary":"#777777","accent":"#A9D8C5","danger":"#F47D84"} as const;
export const colors={...semantic,background:semantic.surface,floating:semantic.surfaceRaised,active:semantic.surfaceSelected,text:semantic.textPrimary,textMuted:semantic.textSecondary,icon:semantic.textPrimary,iconMuted:semantic.textTertiary,separator:semantic.border,selection:semantic.accent,navyDeep:semantic.canvas,navy:semantic.surface,glass:semantic.surfaceRaised,glassStrong:semantic.surfaceSelected,cyan:semantic.accent,blue:semantic.accent,lilac:semantic.textSecondary,mint:semantic.accent,blush:semantic.danger,ice:semantic.textPrimary,scrim:'rgba(0,0,0,.62)'} as const;
export const spacing={xs:4,sm:8,md:12,lg:18,xl:24,xxl:36} as const;
export const radii={sm:8,md:12,lg:16,sheet:20,pill:999} as const;
export const typography={title:{fontSize:32,lineHeight:38,fontWeight:'700' as const,letterSpacing:-1.1},heading:{fontSize:21,lineHeight:27,fontWeight:'700' as const},body:{fontSize:16,lineHeight:23,fontWeight:'400' as const},label:{fontSize:12,lineHeight:16,fontWeight:'600' as const}} as const;
export const motion={fast:140,standard:220,viewer:260} as const;
export const grid={gap:2,columns:3} as const;
