// Generated by scripts/generate-design.cjs from product/design-tokens.json.
const semantic={"canvas":"#000000","surface":"#080808","surfaceRaised":"#101010","surfaceSelected":"#171717","border":"#242424","textPrimary":"#FFFFFF","textSecondary":"#BDBAB4","textTertiary":"#94918C","accent":"#A9D8C5","danger":"#F47D84"} as const;
export const colors={...semantic,background:semantic.surface,floating:semantic.surfaceRaised,active:semantic.surfaceSelected,text:semantic.textPrimary,textMuted:semantic.textSecondary,icon:semantic.textPrimary,iconMuted:semantic.textTertiary,separator:semantic.border,selection:semantic.accent,scrim:'rgba(0,0,0,.62)'} as const;
export const spacing={"xs":4,"sm":8,"md":12,"lg":16,"xl":24,"xxl":32,"section":40,"hero":48} as const;
export const radii={"sm":6,"md":10,"lg":12,"sheet":12,"pill":999} as const;
export const typography={"display":{"fontSize":40,"lineHeight":44,"fontWeight":"400"},"title":{"fontSize":32,"lineHeight":38,"fontWeight":"500"},"heading":{"fontSize":20,"lineHeight":28,"fontWeight":"500"},"body":{"fontSize":16,"lineHeight":24,"fontWeight":"400"},"secondary":{"fontSize":14,"lineHeight":20,"fontWeight":"400"},"label":{"fontSize":13,"lineHeight":18,"fontWeight":"500"},"metadata":{"fontSize":12,"lineHeight":16,"fontWeight":"400"},"micro":{"fontSize":11,"lineHeight":16,"fontWeight":"400"}} as const;
export const motion={"fast":140,"standard":200,"viewer":240} as const;
export const grid={"gap":2,"columns":3} as const;
