/* Product surfaces use account API values. Script text is never evaluated. */
let showAllPasses=false,usageLimit=20,editProject=null,editUndo=[],editRedo=[],editWorkspace='Edit',editFile='scripts/main.py',editBefore=false,editImage=null,editNotice='',projectSearch='';
const HP=HonorableProject;
state.model="SERAN_V1";
nativeTabs.splice(0,nativeTabs.length,['home','Home'],['memories','Memories'],['studio','Studio'],['pass','Pass'],['usage','Usage']);
const balanceView=()=>`<div class=balances><article><small>FREE THIS MONTH</small><b>${accountState?.freeMonthlyRemaining??'—'} / ${accountState?.freeMonthlyTotal??catalog.freeMonthlyCredits??'—'}</b></article><article><small>YOUR MEMORY CREDITS</small><b>${accountState?.balance??'—'}</b><small>Never expires</small></article></div>`;
honorablePass=()=>`<div class=product><h1>Memory Passes</h1><p>Buy once. Use whenever you need it.<br>Purchased Memory Credits never expire.</p>${balanceView()}<h2>${showAllPasses?'All Memory Passes':'Recommended Memory Passes'}</h2><p>Reference USD prices · development purchases only. No payment collected.</p><div class=pass-grid>${(catalog.passes?Object.entries(catalog.passes):[]).slice(0,showAllPasses?31:20).map(([id,credits])=>{const p=productPasses.find(p=>p.id===id);return `<button data-purchase="${id}" ${!webConfig.developmentPurchases||authState!=='online'?'disabled':''}><b>${credits.toLocaleString()}</b><span>Memory Credits</span><strong>$${p?.referenceUsd??'—'} USD</strong><small>One-time purchase · never expires</small></button>`}).join('')}</div><button id=toggle-passes>${showAllPasses?'Show recommended':'Show all 31 passes'}</button><p>Production prices will come from your app store.</p><button id=restore>Restore purchases</button></div>`;
let productPasses=[];
// Server catalog keeps the legacy map shape for older clients and exposes detail separately.
const fetchProductCatalog=async()=>{const c=await webRequest('/account/v1/catalog');catalog=c;productPasses=c.passDetails||[];render()};
const usagePage=()=>`<div class=product><h1>Memory Credits</h1>${balanceView()}<p>Resets ${accountState?.nextResetAt?new Date(accountState.nextResetAt).toLocaleDateString():'—'}<br>Free monthly credits do not roll over.</p>${accountState?.subscription?.status==='ACTIVE'?'<h2>Honorable Studio · Active</h2><p>Studio AI allowance is separate. Production allowance is not configured.</p>':''}<h2>This month</h2>${Object.entries(accountState?.usage?.month||{}).map(([k,v])=>`<div class=ledger-row>${esc(({freeCreditsUsed:'Free credits used',purchasedCreditsUsed:'Purchased credits used',searchCount:'Search count'})[k]||k)}<b>${v}</b></div>`).join('')}<h2>By model</h2>${(catalog.models||[]).map(m=>`<div class=ledger-row>${esc(m.name)} searches<b>${accountState?.usage?.byModel?.[m.model]??0}</b></div>`).join('')}<h2>All time</h2>${Object.entries(accountState?.usage?.allTime||{}).map(([k,v])=>`<div class=ledger-row>${esc(({searchesCompleted:'Searches completed',purchasedCreditsUsed:'Purchased credits used',passesPurchased:'Passes purchased'})[k]||k)}<b>${v}</b></div>`).join('')}<h2>Recent usage</h2>${(accountState?.transactions||[]).slice(0,usageLimit).map(t=>`<div class=ledger-row><span>${esc(t.description)}<small>${new Date(t.createdAt).toLocaleDateString()}</small></span><span>${t.type==='DEBIT'?`${t.freeSpent||0} Free + ${t.purchasedSpent??-t.credits} Purchased used`:t.credits>0?`+${t.credits} ${t.type.startsWith('FREE_')?'Free':'Purchased'}`:'No charge'}</span></div>`).join('')||'<p>No usage yet.</p>'}${(accountState?.transactions?.length||0)>usageLimit?'<button id=usage-more>Load more</button>':''}<h2>Local test library</h2><input id=media-input type=file accept="image/*,video/*" multiple><button id=reindex>Refresh index</button><button data-go=gallery>Browse media</button></div>`;
const studioPage=()=>`<div class=product><h1>Honorable Studio</h1><p>Professional AI photo, video and spatial editing — designed for mobile.</p>${editProject?'<button id=continue-edit>Continue editing</button>':''}<h2>Photo · Free tools</h2><p>Crop, rotate, adjust, undo and save as copy.</p><button data-go=gallery>Choose from your memories</button><h2>Advanced creative tools</h2>${Object.entries(HP.capabilities).filter(([k])=>!['basicEdit','basicPoseRig'].includes(k)).map(([key,c])=>`<button class=ledger-row data-capability=${key}><span>${esc(key.replace(/([A-Z])/g,' $1'))}</span><small>${accountState?.subscription?.status==='ACTIVE'?'':'🔒 '}${c.status.replace('_',' ')}</small></button>`).join('')}<p>Basic still-photo pose: Partial. Segmentation and pixel deformation are not implemented.</p><button id=studio-unlock>${accountState?.subscription?.status==='ACTIVE'?'Studio active':'Unlock Honorable Studio'}</button><p>Monthly subscription pricing is not finalized.</p>${webConfig.developmentPurchases?`<button id=studio-test>${accountState?.subscription?.status==='ACTIVE'?'Remove':'Enable'} test entitlement</button><small>Development only · no charge</small>`:''}</div>`;
const priorProductHome=honorableHome;honorableHome=()=>priorProductHome().replace('</header>','<button class=a-icon-button data-htab=settings aria-label="Account">◉</button></header>').replace(/Terms/g,'Studio').replace(/Know what you sign/g,'Open your creative space').replace(/data-htab=terms/g,'data-htab=studio');
const baseProductSettings=honorableSettings;honorableSettings=()=>`<div class=product><button data-htab=home>Back</button><h1>Account</h1><p>${authState==='offline'?'Offline · previously signed in':'Signed in'}</p><h2>${esc(accountState?.profile?.name||'Your account')}</h2><p>${esc(accountState?.profile?.email||'')}</p>${balanceView()}<p>Studio · ${esc(accountState?.subscription?.status||'NONE')}</p>${[['pass','Manage Memory Passes'],['usage','Usage'],['studio','Studio membership'],['privacy','Privacy & Data'],['models','Search models']].map(([t,l])=>`<button data-htab=${t}>${l}</button>`).join('')}<button id=account-signout>Sign out</button></div>`;
const modelSelector=()=>`<div class=model-row>${(catalog.models||[]).map(m=>`<button data-product-model=${m.model} aria-pressed="${(state.model||'SERAN_V1')===m.model}" ${!m.available?'disabled':''}>${esc(m.name)} · ${m.credits} credit${m.credits===1?'':'s'}${!m.available?'<br>Coming Soon':''}</button>`).join('')}</div>`;
honorableModels=()=>`<div class=product><h1>Seran models</h1>${modelSelector()}${(catalog.models||[]).map(m=>`<h2>${esc(m.name)}</h2><p>${esc(m.description)}</p>`).join('')}</div>`;
const baseProductMemories=memories;memories=()=>modelSelector()+(state.results?.loading?'<button id=cancel-product-search>Cancel search</button>':'')+baseProductMemories();
const priorProductHonorable=honorable;honorable=()=>['studio','usage'].includes(state.honorableTab)?`<div class="page honorable dark a-native">${state.honorableTab==='studio'?studioPage():usagePage()}</div>${honorableDock()}`:priorProductHonorable();
const baseProductViewer=viewer;viewer=()=>editWorkspace==='__editing'?editorPage():baseProductViewer().replace('</header>','<button id=edit-result>Edit</button><button id=share-result>Share</button></header>');
let activeSearch=null;
runSearch=async()=>{if(activeSearch)return;const model=state.model||'SERAN_V1',id=crypto.randomUUID();activeSearch=id;state.results={loading:true};render();try{await webRequest('/account/v1/search/start',{model,requestId:id});const response=await fetch('/api/search?q='+encodeURIComponent(state.query)+'&top=12&model='+encodeURIComponent(model));if(!response.ok)throw Error('Search failed');const result=await response.json();if(activeSearch!==id)return;await webRequest('/account/v1/search/complete',{requestId:id,outcome:result.results?.length?'SUCCESS':'FAILED'});state.results=result;await loadAccount()}catch(error){if(activeSearch!==id)return;try{await webRequest('/account/v1/search/complete',{requestId:id,outcome:'FAILED'})}catch{}state.results={results:[],confident:false,decision:error.message};webNotice=error.message}finally{if(activeSearch===id)activeSearch=null;render()}};
function commitEdit(next){editUndo.push(HP.clone(editProject));if(editUndo.length>50)editUndo.shift();editRedo=[];editProject=next;persistProject()}
function persistProject(){try{localStorage.setItem('honorable-local-project',HP.serialize(editProject))}catch{editNotice='Local project storage is full. Export your project to keep changes.'}}
async function openEditor(item){editProject=HP.create(item);editUndo=[];editRedo=[];editImage=null;editBefore=false;editWorkspace='__editing';activeWorkspace='Edit';editNotice='';if(item.type!=='VIDEO'){const im=new Image();im.onload=()=>{editImage=im;render()};im.onerror=()=>{editNotice='Unable to load original image.';render()};im.src=src(item)}state.app='viewer';render()}
let activeWorkspace='Edit',selectedClip=null;
function syntax(text){return text.split('\n').map((line,i)=>`<span class=code-line><i>${i+1}</i> ${line.split(/(\b(?:project|public|class|void|import|from|def|return|if|else|for|new|float|int)\b|#[^\n]*)/g).map(t=>/^(project|public|class|void|import|from|def|return|if|else|for|new|float|int)$/.test(t)?`<b>${esc(t)}</b>`:t.startsWith('#')?`<em>${esc(t)}</em>`:esc(t)).join('')}</span>`).join('\n')}
function editorPage(){const video=editProject.media[0].kind==='VIDEO',premium=accountState?.subscription?.status==='ACTIVE';return `<div class=studio-editor><header><button id=editor-close aria-label=Back>‹</button><strong>${esc(editProject.name)}</strong><button id=edit-undo ${!editUndo.length?'disabled':''}>Undo</button><button id=edit-redo ${!editRedo.length?'disabled':''}>Redo</button><button id=edit-before>${editBefore?'After':'Before'}</button><button id=edit-export ${video?'disabled':''}>Save as copy</button></header><div class=studio-canvas>${video?`<video controls src="${esc(src({uri:editProject.media[0].uri,type:'VIDEO',timestamp:editProject.timeline.playhead*1000}))}"></video>`:'<canvas id=edit-canvas aria-label="Photo edit preview"></canvas>'}</div><aside class=studio-inspector>${inspector(video,premium)}<p class=note role=status>${esc(editNotice)}</p></aside><nav class=studio-workspaces>${['Edit','Layers',...(video?['Video','Nodes']:[]),'Code','Project'].map(w=>`<button data-workspace=${w}>${w}${['Video','Nodes','Code'].includes(w)&&!premium?' 🔒':''}</button>`).join('')}</nav></div>`}
function inspector(video,premium){if(['Video','Nodes','Code'].includes(activeWorkspace)&&!premium)return '<h3>Honorable Studio</h3><p>This workspace requires an active Studio membership.</p>';if(activeWorkspace==='Edit')return video?'<h3>Video preview</h3><p>Moment context preserved. Sequence editing is a foundation; video export is Coming Soon.</p>':`<h3>Adjust photo · Free</h3>${[['brightness',0,2,.05],['contrast',0,2,.05],['saturation',0,2,.05],['exposure',-2,2,.1],['crop',.2,1,.05]].map(([k,min,max,step])=>`<label>${k}<input data-adjust=${k} type=range min=${min} max=${max} step=${step} value=${editProject.adjustments[k]} aria-label=${k}></label>`).join('')}<div class=tools><button id=rotate-photo>Rotate 90°</button><button id=filter-photo>Monochrome</button><button id=reset-photo>Reset</button><button data-capability=basicPoseRig>Pose · Partial</button></div>`;
if(activeWorkspace==='Layers')return `<h3>Layers</h3>${editProject.layers.map((l,i)=>`<label><input data-layer-visible=${i} type=checkbox ${l.visible?'checked':''}>${esc(l.name)}<input data-layer-opacity=${i} type=range min=0 max=1 step=.05 value=${l.opacity} aria-label="Layer opacity"></label>`).join('')}<p class=note>Image visibility and opacity are rendered. Smart layers and blend engines are Coming Soon.</p>`;
if(activeWorkspace==='Video')return `<h3>Sequence foundation</h3><div class=tools><button id=timeline-add>Add source clip</button><button id=timeline-split>Split at playhead</button><button id=timeline-trim>Trim start to playhead</button><button id=timeline-marker>Add marker</button></div>${editProject.timeline.tracks.map(t=>`<p>${esc(t.kind)} track</p>${t.clips.map(c=>`<button data-clip=${esc(c.id)}>${c.in.toFixed(1)}–${c.out.toFixed(1)}s</button>`).join('')}`).join('')}<div class=studio-timeline><p>Playhead ${editProject.timeline.playhead.toFixed(2)}s</p><input id=playhead type=range min=0 max=300 step=.1 value=${editProject.timeline.playhead}></div><p class=note>Track, clip, marker and keyframe state is serialized. Multi-track rendering and export are not implemented.</p>`;
if(activeWorkspace==='Nodes')return '<h3>Node graph foundation</h3><p>Nodes, ports, parameters and connections share this project state. Graph execution is Coming Soon.</p><button id=view-code>View Project as Code</button>';
if(activeWorkspace==='Project')return `<h3>Project explorer</h3><input id=project-search placeholder="Search project" value="${esc(projectSearch)}"><button id=view-code>View Project as Code</button>${['project.honorable','media/original','layers/layers.json','timeline/sequence.json','nodes/composition.json',...Object.keys(editProject.files)].filter(f=>f.includes(projectSearch)).map(f=>`<button class=file data-file="${esc(f)}">${esc(f)}</button>`).join('')}<div class=tools>${['New script','New folder','Rename / move','Duplicate','Delete'].map((t,i)=>`<button data-file-op=${i}>${t}</button>`).join('')}</div>`;
if(activeWorkspace==='Representation')return `<h3>View Project as Code</h3><pre>${esc(HP.serialize(editProject))}</pre><button id=project-download>Export project</button>`;
const file=editProject.files[editFile];return `<h3>Code · ${file?.language==='java'?'Java':'Python'}</h3><div class=tools><button data-script="scripts/main.py">main.py</button><button data-script="scripts/automation.java">automation.java</button></div><small>${esc(editFile)}</small><textarea id=script-editor aria-label="Script editor" spellcheck=false>${esc(file?.text||'')}</textarea><pre id=syntax-preview>${syntax(file?.text||'')}</pre><div class=tools><button id=script-save>Save</button><button id=script-run>Run</button><button id=script-stop>Stop</button><button id=view-code>Preview project</button></div><p class=note>EDITOR ONLY · execution is unavailable. No filesystem, network, account or billing access.</p><pre>${esc(JSON.stringify(HP.scriptAPI,null,2))}</pre>`}
function renderPixels(canvas,full=false){if(!editImage||!canvas)return;const a=editBefore?HP.defaults():editProject.adjustments;const crop=a.crop,sw=editImage.naturalWidth*crop,sh=editImage.naturalHeight*crop,rot=a.rotation%180!==0;const scale=full?1:Math.min(1,1280/Math.max(sw,sh));canvas.width=Math.max(1,Math.round((rot?sh:sw)*scale));canvas.height=Math.max(1,Math.round((rot?sw:sh)*scale));const ctx=canvas.getContext('2d');ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(a.rotation*Math.PI/180);ctx.filter=`brightness(${a.brightness*Math.pow(2,a.exposure)}) contrast(${a.contrast}) saturate(${a.saturation}) ${a.filter==='mono'?'grayscale(1)':''}`;const layer=editProject.layers[0];ctx.globalAlpha=editBefore?1:layer.visible?layer.opacity:0;ctx.drawImage(editImage,(editImage.naturalWidth-sw)/2,(editImage.naturalHeight-sh)/2,sw,sh,-sw*scale/2,-sh*scale/2,sw*scale,sh*scale)}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
const priorStudioBind=window.bindWebTest;window.bindWebTest=()=>{priorStudioBind();const on=(id,fn)=>screen.querySelector('#'+id)?.addEventListener('click',fn);
on('cancel-product-search',async()=>{const id=activeSearch;if(!id)return;activeSearch=null;state.results=null;render();try{await webRequest('/account/v1/search/complete',{requestId:id,outcome:'CANCELLED'})}catch(e){webNotice=e.message;render()}});
on('toggle-passes',()=>{showAllPasses=!showAllPasses;render()});on('usage-more',()=>{usageLimit+=20;render()});on('studio-unlock',()=>{webNotice='Studio is a monthly membership for advanced creative tools. Store subscriptions are not enabled yet.';render()});on('studio-test',()=>webAction(async()=>{await webRequest('/account/dev/studio',{active:accountState?.subscription?.status!=='ACTIVE'});await loadAccount()}));
screen.querySelectorAll('[data-product-model]').forEach(b=>b.onclick=()=>{state.model=b.dataset.productModel;render()});
screen.querySelectorAll('[data-capability]').forEach(b=>b.onclick=()=>{const result=HP.route(b.dataset.capability,{studio:accountState?.subscription?.status==='ACTIVE'});const message=result.reason==='STUDIO_REQUIRED'?'This advanced tool requires Honorable Studio.':result.blocker||'This capability is Coming Soon.';webNotice=message;editNotice=message;render()});
on('edit-result',()=>openEditor(state.preview||state.media[state.opened]));on('share-result',async()=>{const item=state.preview||state.media[state.opened];if(navigator.share){try{await navigator.share({title:item.name,url:new URL(src(item),location.href).href})}catch{}}else{webNotice='Sharing is unavailable in this browser. Use Open to access the media.';render()}});
on('continue-edit',()=>{editWorkspace='__editing';state.app='viewer';render()});on('editor-close',()=>{editWorkspace='Edit';render()});
on('edit-undo',()=>{editRedo.push(HP.clone(editProject));editProject=editUndo.pop();persistProject();render()});on('edit-redo',()=>{editUndo.push(HP.clone(editProject));editProject=editRedo.pop();persistProject();render()});on('edit-before',()=>{editBefore=!editBefore;render()});
screen.querySelectorAll('[data-adjust]').forEach(input=>{input.oninput=()=>{const preview=HP.clone(editProject);preview.adjustments[input.dataset.adjust]=+input.value;const old=editProject;editProject=preview;renderPixels(screen.querySelector('#edit-canvas'));editProject=old};input.onchange=()=>{const p=HP.clone(editProject);p.adjustments[input.dataset.adjust]=+input.value;commitEdit(p);render()}});
for(const [id,change]of [['rotate-photo',a=>a.rotation=(a.rotation+90)%360],['filter-photo',a=>a.filter=a.filter==='mono'?'none':'mono'],['reset-photo',a=>Object.assign(a,HP.defaults())]])on(id,()=>{const p=HP.clone(editProject);change(p.adjustments);commitEdit(p);render()});
on('edit-export',()=>{const canvas=document.createElement('canvas'),before=editBefore;editBefore=false;renderPixels(canvas,true);editBefore=before;canvas.toBlob(blob=>{if(!blob){editNotice='Export failed';render();return}downloadBlob(blob,'Honorable-copy.png');editProject.exports.push({name:'Honorable-copy.png',createdAt:new Date().toISOString()});persistProject();editNotice='Saved as a new PNG copy. Original preserved.';render()},'image/png')});
screen.querySelectorAll('[data-workspace]').forEach(b=>b.onclick=()=>{if(['Video','Nodes','Code'].includes(b.dataset.workspace)&&accountState?.subscription?.status!=='ACTIVE'){editNotice='This workspace requires Honorable Studio.'}else{activeWorkspace=b.dataset.workspace;editNotice=''}render()});
screen.querySelectorAll('[data-layer-visible],[data-layer-opacity]').forEach(input=>input.onchange=()=>{const p=HP.clone(editProject);if(input.dataset.layerVisible!==undefined)p.layers[+input.dataset.layerVisible].visible=input.checked;else p.layers[+input.dataset.layerOpacity].opacity=+input.value;commitEdit(p);render()});
screen.querySelector('#playhead')?.addEventListener('input',e=>{editProject.timeline.playhead=+e.target.value;const video=screen.querySelector('video');if(video)video.currentTime=+e.target.value;persistProject()});on('view-code',()=>{activeWorkspace='Representation';render()});on('project-download',()=>downloadBlob(new Blob([HP.serialize(editProject)],{type:'application/json'}),'project.honorable'));
screen.querySelectorAll('[data-script]').forEach(b=>b.onclick=()=>{editFile=b.dataset.script;render()});on('script-save',()=>{commitEdit(HP.fileOperation(editProject,'save',editFile,null,screen.querySelector('#script-editor').value));editNotice='Script saved locally.';render()});on('script-run',()=>{editNotice=HP.sandbox.validate(editProject.files[editFile].language,screen.querySelector('#script-editor').value).message;render()});on('script-stop',()=>{editNotice='No script is running.';render()});
screen.querySelector('#project-search')?.addEventListener('change',e=>{projectSearch=e.target.value;render()});screen.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{if(editProject.files[b.dataset.file]?.kind==='script'){editFile=b.dataset.file;if(accountState?.subscription?.status==='ACTIVE')activeWorkspace='Code';else editNotice='The Code workspace requires Studio.'}else activeWorkspace='Representation';render()});
screen.querySelectorAll('[data-file-op]').forEach(b=>b.onclick=()=>{const i=+b.dataset.fileOp,from=prompt(i<2?'Virtual project path':'Existing virtual path',i<2?'scripts/new.py':editFile);if(!from)return;const to=i===2||i===3?prompt('Destination path'):null;if(i===4&&!confirm('Delete this virtual file/folder and its children?'))return;try{commitEdit(HP.fileOperation(editProject,['create','folder','move','duplicate','delete'][i],from,to));editNotice='Project updated'}catch(e){editNotice=e.message}render()});
screen.querySelector('#script-editor')?.addEventListener('input',e=>{screen.querySelector('#syntax-preview').innerHTML=syntax(e.target.value)});
const timelineChange=op=>{try{commitEdit(HP.timelineOperation(editProject,op,{studio:accountState?.subscription?.status==='ACTIVE'}));editNotice='Timeline state updated. Multi-track rendering is Coming Soon.'}catch(e){editNotice=e.message}render()};
on('timeline-add',()=>{const duration=screen.querySelector('video')?.duration;if(!Number.isFinite(duration)||duration<=0){editNotice='Wait for video metadata before adding a clip.';render();return}if(!editProject.timeline.tracks.length)commitEdit(HP.timelineOperation(editProject,{type:'addTrack',id:'video-1',kind:'video'},{studio:accountState?.subscription?.status==='ACTIVE'}));timelineChange({type:'addClip',trackId:'video-1',id:crypto.randomUUID(),mediaId:'source',duration})});
screen.querySelectorAll('[data-clip]').forEach(b=>b.onclick=()=>{selectedClip=b.dataset.clip;editNotice='Clip selected';render()});
on('timeline-split',()=>timelineChange({type:'split',trackId:'video-1',clipId:selectedClip,id:crypto.randomUUID(),time:editProject.timeline.playhead}));
on('timeline-trim',()=>{const clip=editProject.timeline.tracks.flatMap(t=>t.clips).find(c=>c.id===selectedClip);timelineChange({type:'trim',trackId:'video-1',clipId:selectedClip,in:editProject.timeline.playhead,out:clip?.out})});
on('timeline-marker',()=>timelineChange({type:'marker',time:editProject.timeline.playhead,label:'Marker'}));
renderPixels(screen.querySelector('#edit-canvas'));
};
fetchProductCatalog().catch(()=>{});render();
