/* Optional interaction analytics. Strict server schema; no content, paths, names or queries. */
(()=>{
 let queue=[],timer=null,account=null,wasEditor=false,lastWorkspace='',lastExports=0,lastSaveFailure=false,editorStarted=0;
 const disabled=()=>localStorage.getItem('honorable-analytics-disabled')==='1';
 function track(type,metadata={}){try{if(disabled()||authState!=='online'||!accountState?.accountId)return;const id=accountState.accountId;if(account!==id){queue=[];account=id}if(queue.length>=60)queue.shift();queue.push({id:crypto.randomUUID(),type,metadata});if(!timer)timer=setTimeout(flush,1500)}catch{/* Telemetry never interrupts interaction. */}}
 async function flush(){timer=null;const batch=queue.splice(0,20),owner=account;try{if(!batch.length||owner!==accountState?.accountId||authState!=='online'||disabled())return;await fetch('/account/v1/analytics',{method:'POST',credentials:'same-origin',signal:AbortSignal.timeout(3000),headers:{'Content-Type':'application/json','X-Honorable-Web':'1','X-Honorable-Platform':'WEB_TEST','X-Honorable-App-Version':'0.2.0'},body:JSON.stringify({events:batch})})}catch{/* Best effort, bounded queue; no retry loop. */}finally{if(queue.length&&!timer)timer=setTimeout(flush,1500)}}
 window.HonorableTelemetry={track,flush};
 document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.htab==='pass'||b.dataset.purchase)track('pass_interest');const tool={'rotate-photo':'rotate','filter-photo':'monochrome','reset-photo':'reset','edit-undo':'undo','edit-redo':'redo'}[b.id];if(tool)track('edit_tool_used',{tool});if(b.dataset.capability)track('feature_interest',{feature:b.dataset.capability});else if(b.dataset.category){const feature={Video:'videoSequence',Animate:'rigAnimation','3D':'geometry',Code:'code',Nodes:'nodes'}[b.dataset.category];if(feature)track('feature_interest',{feature})}if(b.dataset.aResult!==undefined||b.dataset.library!==undefined){const result=b.dataset.aResult!==undefined?filteredNativeResults()[+b.dataset.aResult]:state.media[+b.dataset.library];if(result)track('result_opened',{mediaType:result.type,videoMoment:result.type==='VIDEO'&&Number.isFinite(result.timestamp)})}},true);
 document.addEventListener('change',event=>{const tool=event.target.dataset?.adjust;if(['crop','brightness','contrast','saturation','exposure'].includes(tool))track('edit_tool_used',{tool})},true);
 new MutationObserver(()=>{try{if(account!==accountState?.accountId){queue=[];account=accountState?.accountId;wasEditor=false;lastWorkspace='';lastExports=0}const open=editWorkspace==='__editing'&&state.app==='viewer'&&!!editProject;if(open&&!wasEditor){editorStarted=Date.now();track('editor_opened',{mediaType:editProject.media[0].kind,fromSearch:!!state.results?.requestId});lastExports=editProject.exports.length}if(open){if(editNotice==='Export failed'&&!lastSaveFailure)track('client_error',{errorCode:'SAVE_FAILED'});lastSaveFailure=editNotice==='Export failed';const workspace=activeWorkspace==='Code'?(editFile.endsWith('.java')?'Java':'Python'):activeWorkspace;if(workspace!==lastWorkspace&&['Layers','Project','Python','Java','Nodes','Video','Code'].includes(workspace))track('workspace_opened',{workspace});lastWorkspace=workspace;if(editProject.exports.length>lastExports)track('edit_saved',{mediaType:editProject.media[0].kind,fromSearch:!!state.results?.requestId});lastExports=editProject.exports.length}if(wasEditor&&!open&&editorStarted){track('editor_closed',{durationMs:Math.min(3600000,Date.now()-editorStarted)});editorStarted=0}wasEditor=open;}catch{/* Product can initialize independently. */}}).observe(document.querySelector('#screen'),{childList:true,subtree:true});
})();
