// Copy only the Lucide paths used by the web UI from the installed native icon family.
const fs = require("node:fs"),
  path = require("node:path"),
  vm = require("node:vm");
const root = path.resolve(__dirname, ".."),
  source = path.join(
    root,
    "mobile-react-native/node_modules/lucide-react-native"
  );
const names = {
  home: "house",
  memories: "images",
  studio: "sliders-horizontal",
  pass: "ticket",
  usage: "chart-no-axes-column",
  account: "circle-user-round",
  settings: "sliders-horizontal",
  search: "search",
  arrow: "arrow-up-right",
  up: "arrow-up",
  back: "arrow-left",
  chevron: "chevron-right",
  close: "x",
  lock: "lock-keyhole",
  check: "check",
  play: "play",
  image: "image",
  film: "film",
  layers: "layers",
  crop: "crop",
  more: "ellipsis",
  code: "code",
  terms: "file-text",
  activity: "chart-no-axes-column",
  text: "file-text",
  upload: "upload",
  link: "link",
  spark: "image",
};
const icons = {};
for (const [key, name] of Object.entries(names)) {
  const text = fs.readFileSync(
    path.join(source, "dist/esm/icons", name + ".mjs"),
    "utf8"
  );
  const array = text.slice(
    text.indexOf(", [") + 2,
    text.lastIndexOf("]);") + 1
  );
  const nodes = vm.runInNewContext("(" + array + ")", {}, { timeout: 1000 });
  icons[key] = nodes
    .map(
      ([tag, attrs]) =>
        "<" +
        tag +
        " " +
        Object.entries(attrs)
          .filter(([k]) => k !== "key")
          .map(([k, v]) => `${k}="${v}"`)
          .join(" ") +
        "/>"
    )
    .join("");
}
const dest = path.join(root, "android-app/test-lab/web-test-shell");
fs.writeFileSync(
  path.join(dest, "android-icons.js"),
  "/* Lucide — ISC. See Lucide-LICENSE.txt. Generated by scripts/generate-icons.cjs. */\nconst honorableIcons=" +
    JSON.stringify(icons) +
    ";\n"
);
fs.copyFileSync(
  path.join(source, "LICENSE"),
  path.join(dest, "Lucide-LICENSE.txt")
);
