const {chromium}=require('../../Honorable-mobile-app-main/ui-previews/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage();
await page.setContent('<title>Pride and Prejudice — Chapter 2</title><main><p>Elizabeth Bennet met Darcy in England. Darcyshire.</p><a href="#">Darcy</a><textarea>Darcy</textarea></main>');
await page.evaluate(()=>{window.roleStore={};window.chrome={storage:{local:{get:async key=>({[key]:window.roleStore[key]}),set:async value=>Object.assign(window.roleStore,value),remove:async key=>{delete window.roleStore[key];}}},runtime:{sendMessage:async()=>({data:{facts:[{label:'Occupation',value:'Test role'}],biography:'Expanded fixture biography.'}}),onMessage:{addListener:f=>window.receive=f}}};});
await page.addScriptTag({path:require('node:path').resolve(__dirname,'../content.js')});
const send=message=>page.evaluate(message=>new Promise(resolve=>window.receive(message,{},resolve)),message);
assert.equal((await send({type:'nc-title'})).title,'Pride and Prejudice');
const entries=[{id:'Q1',name:'Elizabeth Bennet',aliases:[],kind:'character',description:'A character',source:'https://www.wikidata.org/wiki/Q1'},{id:'Q2',name:'Darcy',aliases:[],kind:'character',description:'Another character'},{id:'Q3',name:'England',aliases:[],kind:'place',description:'A place'}];
assert.equal((await send({type:'nc-highlight',entries})).count,3);
assert.equal(await page.locator('a mark,textarea mark').count(),0);
await page.locator('mark').first().click();assert.equal(await page.locator('[data-novel-companion="card"]').count(),1);
await page.getByRole('dialog').waitFor();assert.equal(await page.locator('.portrait').innerText(),'');assert.match(await page.getByRole('dialog').innerText(),/Expanded fixture biography/);assert.match(await page.getByRole('dialog').innerText(),/Not available from current sources/);
assert.match(await page.locator('.role-tags').innerText(),/Role unconfirmed/);
assert.match(await page.getByRole('dialog').innerText(),/Power scale: Not confirmed for this chapter/);
await page.getByText('Add your power / rank notes',{exact:true}).click();
await page.getByLabel('Power and rank notes').fill('Chapter 10: personal rank note');await page.getByRole('button',{name:'Save notes',exact:true}).click();
await page.waitForFunction(()=>Object.values(window.roleStore).includes('Chapter 10: personal rank note'));
await page.getByText('Edit role tags',{exact:true}).click();await page.getByLabel('MC · Main Character',{exact:true}).check();
assert.match(await page.locator('.role-tags').innerText(),/MC/);
await page.keyboard.press('Escape');await page.locator('mark').first().click();
await page.waitForFunction(()=>document.querySelector('[data-novel-companion="card"]').shadowRoot.querySelector('.role-tags').textContent.includes('MC'));
const originalDesktopWidth=1280;
let pane=await page.locator('body').boundingBox(), sidebar=await page.getByRole('dialog').boundingBox();
assert.ok(pane.x+pane.width<=sidebar.x+1,'Desktop reading area must end before sidebar');
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(100);
pane=await page.locator('body').boundingBox();sidebar=await page.getByRole('dialog').boundingBox();
assert.ok(pane.y+pane.height<=sidebar.y+1,'Mobile reading area must end above information pane');
assert.ok(pane.height>400,'Mobile retains a usable reading area');
await page.keyboard.press('Escape');assert.equal(await page.locator('body').evaluate(el=>el.style.position),'');
await page.setViewportSize({width:originalDesktopWidth,height:720});
assert.equal(await page.locator('[data-novel-companion="card"]').count(),0);
await page.evaluate(()=>{const p=document.createElement('p');p.textContent='Darcy arrived.';document.querySelector('main').append(p);});await page.waitForTimeout(400);assert.equal(await page.locator('mark').count(),4);
await page.evaluate(()=>{const p=document.createElement('p');p.id='changing';p.textContent='Nobody';document.querySelector('main').append(p);});await page.waitForTimeout(400);await page.evaluate(()=>document.querySelector('#changing').firstChild.data='England');await page.waitForTimeout(400);assert.equal(await page.locator('#changing mark').count(),1);
await send({type:'nc-remove'});assert.equal(await page.locator('mark').count(),0);assert.match(await page.locator('main').innerText(),/Darcyshire/);
await page.route('https://reading.example/**',route=>route.fulfill({contentType:'text/html',body:'<main><p>Elizabeth Bennet met Darcy in England.</p></main>'}));
await page.goto('https://reading.example/novel/pride-and-prejudice/chapter-2');
await page.evaluate(entries=>{window.chrome={runtime:{sendMessage:async message=>{window.detectedTitle=message.title;return {data:{entries}};},onMessage:{addListener:fn=>window.receive=fn}}};},entries);
await page.addScriptTag({path:require('node:path').resolve(__dirname,'../content.js')});
await page.locator('mark').first().waitFor();assert.equal(await page.evaluate(()=>window.detectedTitle),'pride and prejudice');
await send({type:'nc-toggle'});assert.equal(await page.locator('mark').count(),0);
await send({type:'nc-toggle'});await page.locator('mark').first().waitFor();
await page.evaluate(()=>{const script=document.createElement('script');script.type='text/plain';script.textContent='UNWANTED SCRIPT';document.querySelector('main').append(script);const nav=document.createElement('nav');nav.textContent='UNWANTED AD';document.querySelector('main').append(nav);});
const snapshot=await send({type:'nc-snapshot'});assert.match(snapshot.text,/Elizabeth Bennet/);assert.ok(!snapshot.text.includes('UNWANTED'));assert.equal(snapshot.url,'https://reading.example/novel/pride-and-prejudice/chapter-2');
await page.evaluate(()=>{const main=document.querySelector('main');const h=document.createElement('h1');h.textContent='Pride and Prejudice — Chapter 2';main.prepend(h);const p=document.createElement('p');p.textContent='Elizabeth walked toward the village to meet her family. The village was quiet after the storm had passed. Her family waited near the old bridge outside the village. Together they returned home before the evening rain began.';main.append(p);});
await page.getByRole('button',{name:'Show current chapter summary',exact:true}).waitFor();
await page.getByRole('button',{name:'Show current chapter summary',exact:true}).click();
await page.getByRole('dialog').waitFor();assert.match(await page.getByRole('dialog').innerText(),/Chapter summary/i);assert.match(await page.getByRole('dialog').innerText(),/village/);assert.equal(await page.locator('.portrait').count(),0);
await browser.close();console.log('Browser smoke passed: title, matching, exclusions, cards, Escape, dynamic text, removal.');})().catch(e=>{console.error(e);process.exit(1)});
