import React from 'react';
import {ActivityIndicator,Image,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useMemoryPass} from '../passes/MemoryPassContext';
export function AccountGate({children}:{children:React.ReactNode}){
 const auth=useMemoryPass();
 if(auth.signedIn)return <>{children}</>;
 if(auth.status==='restoring'||auth.status==='signing-in')return <View style={styles.launch}><Text style={styles.wordmark}>honorable</Text><ActivityIndicator color="#aaa"/><Text style={styles.small}>Opening your memories…</Text></View>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.wordmark}>honorable</Text><Image source={require('./welcome.png')} style={styles.photo} accessibilityLabel="A quiet beach memory"/><Text style={styles.title}>Find any{'\n'}memory.</Text><Text style={styles.copy}>You remember the moment.{'\n'}Honorable finds it.</Text><Pressable accessibilityRole="button" disabled={!auth.googleConfigured} style={styles.button} onPress={auth.signInGoogle}><Text style={styles.buttonText}>Continue with Google</Text></Pressable>{!!auth.error&&<Text accessibilityRole="alert" style={styles.small}>{auth.error}</Text>}<Text style={styles.privacy}>Your memories stay yours.</Text><Text style={styles.small}>Signing in keeps your Memory Passes, credits and account access connected across sessions and devices.</Text>{auth.status==='unavailable'&&<Pressable onPress={auth.refresh}><Text style={styles.privacy}>Try restoring again</Text></Pressable>}</ScrollView></SafeAreaView>
}
export function AccountPanel(){const auth=useMemoryPass();return <View style={styles.panel}><Text style={styles.privacy}>{auth.account?.profile?.name||'Your account'}</Text><Text style={styles.small}>{auth.account?.profile?.email||''}</Text><Text style={styles.small}>{auth.status==='offline'?'Offline · previously signed in':'Signed in'}</Text><Text style={styles.privacy}>Free this month: {auth.account?.freeMonthlyRemaining??0} / {auth.account?.freeMonthlyTotal??"—"}</Text><Text style={styles.privacy}>{auth.account?.balance??0} Purchased Memory Credits</Text><Text style={styles.small}>Memory Pass · {(auth.account?.balance||0)>0?'credits available':'no credits yet'}{'\n'}Studio · {auth.account?.subscription.status||'NONE'}</Text><Pressable onPress={auth.signOut} accessibilityRole="button" style={styles.button}><Text style={styles.buttonText}>Sign out</Text></Pressable></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#000'},launch:{flex:1,backgroundColor:'#000',alignItems:'center',justifyContent:'center',gap:18},content:{padding:26,paddingBottom:40},wordmark:{color:'#fff',fontSize:23,fontWeight:'700',letterSpacing:-.6},photo:{height:180,width:'100%',marginVertical:28,opacity:.65},title:{color:'#fff',fontSize:52,lineHeight:51,fontWeight:'800',letterSpacing:-2},copy:{color:'#aaa',fontSize:17,lineHeight:25,marginTop:16,marginBottom:24},button:{backgroundColor:'#fff',borderRadius:28,padding:16,alignItems:'center',marginVertical:16},buttonText:{fontSize:16,fontWeight:'600',color:'#000'},privacy:{color:'#fff',fontSize:14,fontWeight:'700',marginTop:18,marginBottom:10},small:{color:'#999',fontSize:12,lineHeight:18},panel:{backgroundColor:'#111',borderRadius:28,padding:22,marginVertical:16}});
