/* Internal beta operations, using the same server-enforced admin session. */
let betaData=null;
const betaOptions=values=>values.map(v=>`<option>${esc(v)}</option>`).join('');
const betaSelect=(name,values)=>`<label>${esc(name)}<select name="${name}">${betaOptions(values)}</select></label>`;
const betaInput=(name,type='text',required=true)=>`<label>${esc(name)}<input name="${name}" type=${type} ${required?'required':''} maxlength=4000></label>`;
const betaForm=(action,title,fields)=>panel(title,`<form data-beta-action="${action}" class=filters>${fields}<button>${esc(title)}</button></form>`);
async function betaView(){
 try{const b=await api('beta');if(tab!=='Beta')return;betaData=b;const operator=session.role!=='VIEWER';
 let html=stats([['Active testers',b.summary.active],['Invites pending',b.summary.pending],['Beta DAU',b.summary.dau],['Feedback this week',b.summary.feedbackThisWeek],['Open bugs',b.summary.openBugs],['Critical bugs',b.summary.criticalBugs],['Crash-free sessions %',b.summary.crashFreeSessions],['Release gate',b.gate.status],['Marketing ready',b.gate.marketingReady?'TRUE':'FALSE']])+`<p class=coverage>${esc(b.environment)} · ${esc(b.channel)} · Access ${b.required?'INVITE REQUIRED':'optional enrollment'} · Crashes are not inferred from errors.</p>`;
 html+=panel('Build adoption',stats([['Latest version',b.adoption.current?.version],['Release platform',b.adoption.current?.platform],['Current build % · known builds',b.adoption.currentPercent],['Previous build %',b.adoption.previousPercent],['Outdated',b.adoption.outdated],['Unknown build',b.adoption.unknownBuilds]])+table(b.adoption.history,[['Observed','at',date],['Version','version'],['Build','buildNumber']]));
 html+=panel('Beta success and quality',stats([['Activated',b.summary.activated],['Searches / tester',b.summary.searchesPerTester],['Successful searches',b.summary.successfulSearches],['Search latency ms',b.summary.searchLatencyMs],['Explicit search feedback',b.summary.searchFeedback],['Editor saves',b.editor.saves],['Save failures',b.editor.saveFailures],['Save success %',b.editor.saveSuccessRate],['Average edit session ms',b.editor.averageSessionMs]])+table(b.retention,[['Day','day'],['Eligible','eligible'],['Returned','returned'],['Retention %','rate']])+'<p>Targets are optional operator configuration. Retention is limited to observed, retained beta activity.</p>');
 html+=panel('Configured beta targets',table(Object.entries(b.targets).map(([metric,target])=>({metric,target,observed:b.summary[metric]})),[['Metric','metric'],['Target','target'],['Observed','observed']]));
 html+=panel('Tester directory',`<form id=beta-filter class=filters><input name=q placeholder="Account / ${operator?'email / ':''}cohort / version / platform"><select name=cohort><option value="">All cohorts</option>${betaOptions([...new Set(b.directory.map(t=>t.cohort))])}</select><select name=platform><option value="">All platforms</option>${betaOptions([...new Set(b.directory.map(t=>t.context?.platform).filter(Boolean))])}</select><select name=version><option value="">All versions</option>${betaOptions([...new Set(b.directory.map(t=>t.context?.appVersion).filter(Boolean))])}</select><select name=activity><option value="">Any activity</option><option value=ACTIVE>Active in 7 days</option><option value=INACTIVE>Inactive in 7 days</option></select><select name=status><option value="">All statuses</option>${betaOptions(['INVITED','ACTIVE','PAUSED','REMOVED'])}</select><label><input type=checkbox name=feedback>Has feedback</label><label><input type=checkbox name=errors>Has errors</label><button>Filter</button></form><div id=beta-directory></div><div id=beta-tester-detail></div>`);
 html+=panel('Bug reports',table(b.feedback,[['Bug','id'],['Title','title',esc],['Status','status'],['Severity','severity'],['Category','category'],['Reporter','reporter'],['Version / platform','context',v=>esc([v?.appVersion,v?.platform].filter(Boolean).join(' / '))],['Assigned','assignedOwner'],['Notes','notes',v=>(v||[]).map(n=>esc(n.text)).join('<br>')],['Description · tester supplied','description',esc],['Consented attachments','attachments',v=>(v||[]).map(a=>`<a href="/admin/api/beta/attachment/${esc(a.id)}" download>${esc(a.kind)}</a>`).join(' ')],['Updated','updatedAt',date]]));
 html+=panel('Grouped errors',table(b.errors,[['Code','code'],['Platform','platform'],['Version','version'],['Count','count'],['Affected users','affectedUsers'],['First seen','firstSeen',date],['Last seen','lastSeen',date]]));
 html+=panel('Crash / ANR groups',table(b.crashes,[['Kind','kind'],['Version','version'],['Platform','platform'],['Count','count'],['Affected users','affectedUsers'],['First seen','firstSeen',date],['Last seen','lastSeen',date]])+`<p>${esc(b.coverage.crashes)}</p>`);
 html+=panel('Cohort performance',table(b.cohorts,[['Cohort','cohort'],['Testers','testers'],['Authenticated startup ms','startupMs'],['Search ms','searchLatencyMs'],['Index ms','indexTime'],['Editor response ms','editorResponseMs'],['Memory pressure','memoryPressure'],['Proxy uses','proxyUsage'],['Crash reports','crashes']]));
 html+=panel('Search quality · explicit tester feedback',table(b.quality,[['Model / version','group'],['Correct','correct'],['Wrong','wrong'],['Not found','notFound'],['Timestamp complaints','timestampWrong'],['Too slow','tooSlow'],['Correct %','correctRate']]));
 html+=panel('Device coverage · observed families',table(b.deviceCoverage,[['Platform','platform'],['Manufacturer','manufacturer'],['Family','modelFamily'],['OS','osVersion'],['RAM','ramClass'],['Tier','capabilityClass'],['Vulkan','vulkan'],['Testers','testers'],['Errors','errors'],['Crash rate','crashRate']])+ '<p>Unobserved devices are not certified. Android metrics describe observed runs only; unsupported OS exit-reason collection and unobserved devices are not treated as crash-free.</p>');
 html+=panel('Planned device test matrix',table(b.plannedDevices,[['ID','id'],['Manufacturer','manufacturer'],['Family','modelFamily'],['Android','osVersion'],['RAM','ramClass'],['Vulkan','vulkan'],['Tier','capabilityClass'],['Status','status'],['Evidence','evidence',esc]]));
 html+=panel('Known issues',table(b.knownIssues,[['ID','id'],['Title','title',esc],['Severity','severity'],['Platform','platform'],['Version','version'],['Status','status'],['Tester text','testerText',esc]]));
 html+=panel('Release registry',table(b.releases,[['ID','id'],['Version','version'],['Build','buildNumber'],['Commit','commit'],['Platform','platform'],['Channel','channel'],['Status','status'],['Update','updateLevel'],['Tester notes','testerNotes',esc],...(operator?[['Internal notes','internalNotes',esc]]:[])]));
 html+=panel('Release evidence checklist',table(b.gate.missing.map(check=>({check,status:'NOT VERIFIED'})),[['Check','check'],['Status','status']])+`<p>Demo A: ${b.gate.demoA?'ready':'unverified'} · Demo B: ${b.gate.demoB?'ready':'not ready'} · Demo C: ${b.gate.demoC?'ready':'unverified'}. Evidence is specific to the selected latest build.</p>`);
 html+=panel('Verified marketing handoff',b.gate.marketingReady?table(b.gate.assets.filter(a=>a.approved),[['Kind','kind'],['Reference','reference',esc],['Approved claim','claim',esc]]):'<p>Locked until MARKETING READY. Approved evidence is recorded per release; unfinished capabilities are not claims.</p>');
 html+=panel('Effective rollout rules',table(b.flags,[['Flag','flag'],['Scope','scope'],['Target','target'],['Enabled','enabled',v=>v?'Enabled':'Disabled'],['Reason','reason',esc]])+'<p>A GLOBAL disable wins over all overrides. Flags cannot unlock V3, unsupported execution or bypass Studio entitlements.</p>');
 if(operator){
 html+=betaForm('device','Record device coverage',betaInput('id','text',false)+betaInput('manufacturer')+betaInput('modelFamily')+betaInput('osVersion')+betaSelect('ramClass',['UNKNOWN','LOW','MID','HIGH'])+betaSelect('vulkan',['UNKNOWN','SUPPORTED','UNSUPPORTED'])+betaSelect('capabilityClass',['UNKNOWN','LOW','MID','HIGH'])+betaSelect('status',['NOT_TESTED','TESTED','ISSUE'])+betaInput('evidence','text',false));
 html+=betaForm('target','Set optional beta target',betaSelect('metric',['invited','activated','dau','successfulSearches','searchFeedback','crashFreeSessions','searchesPerTester','studioInterest','memoryPassInterest'])+betaInput('value','number'));
 html+=betaForm('invite','Invite tester',betaInput('email','email')+betaSelect('cohort',['FOUNDERS','FRIENDS_FAMILY','EARLY_TESTERS','CREATORS','HEAVY_MEDIA','LOW_END_DEVICE','VIDEO_TESTERS']));
 html+=betaForm('tester','Update tester',betaInput('id')+betaSelect('status',['ACTIVE','PAUSED','REMOVED','INVITED'])+betaSelect('cohort',['FOUNDERS','FRIENDS_FAMILY','EARLY_TESTERS','CREATORS','HEAVY_MEDIA','LOW_END_DEVICE','VIDEO_TESTERS']));
 html+=betaForm('triage','Triage bug',betaInput('id')+betaSelect('status',['NEW','TRIAGED','IN_PROGRESS','FIXED','VERIFIED','CLOSED'])+betaSelect('severity',['S1','S2','S3','S4'])+betaInput('assignedOwner','text',false)+betaInput('note'));
 html+=betaForm('flag','Set rollout flag',betaSelect('flag',['studio_enabled','video_search_enabled','v3_visible','rig_preview_enabled','nodes_visible','code_workspace_visible'])+betaSelect('scope',['GLOBAL','COHORT','ACCOUNT'])+betaInput('target','text',false)+betaSelect('enabled',['false','true'])+betaInput('reason'));
 html+=betaForm('release','Register release',betaSelect('platform',['ANDROID','WEB_TEST','IOS','ALL'])+betaInput('version')+betaInput('buildNumber')+betaInput('commit')+`<input type=hidden name=channel value="${esc(b.channel)}">`+betaSelect('status',['DRAFT','TESTING','RELEASED','WITHDRAWN'])+betaInput('internalNotes')+betaInput('testerNotes')+betaSelect('updateLevel',['OPTIONAL','RECOMMENDED','REQUIRED'])+betaInput('minimumBuild','text',false));
 html+=betaForm('release-status','Change release status',betaInput('id')+betaSelect('status',['DRAFT','TESTING','RELEASED','WITHDRAWN'])+betaInput('reason'));
 html+=betaForm('asset','Approve marketing evidence',betaInput('releaseId')+betaSelect('kind',['SCREENSHOT','DEMO_A','DEMO_B','DEMO_C','CLAIM'])+betaInput('reference')+betaInput('claim')+betaSelect('approved',['false','true']));
 html+=betaForm('check','Record release evidence',betaInput('releaseId')+betaSelect('check',['code_committed','tests_pass','android_actions_pass','artifact_exists','version_bumped','release_notes','flags_correct','secrets_configured','no_dev_purchases','v3_locked','auth_verified','pass_verified','usage_verified','real_photo_demo','search_ledger','editor_save','privacy_check','admin_healthy'])+betaSelect('passed',['false','true'])+betaInput('evidence'));
 html+=betaForm('issue','Record known issue',betaInput('id','text',false)+betaInput('title')+betaInput('testerText','text',false)+betaSelect('severity',['S1','S2','S3','S4'])+betaSelect('platform',['ALL','ANDROID','WEB_TEST','IOS'])+betaInput('version','text',false)+betaSelect('status',['OPEN','RESOLVED']));
 html+=panel('Privacy requests',table(b.requests,[['ID','id'],['Account','accountId'],['Type','type'],['Status','status']]))+betaForm('request','Review privacy request',betaInput('id')+betaSelect('status',['IN_REVIEW','FULFILLED','DECLINED'])+betaInput('note'));
 html+='<button id=beta-export>Export aggregate JSON</button><p>Invites are recorded internally. No email is sent automatically. Use the reviewed invitation template.</p>';
 }
 document.querySelector('#content').insertAdjacentHTML('beforeend',`<div id=beta-content>${html}</div>`);
 const draw=()=>{const f=document.querySelector('#beta-filter'),q=f.elements.q.value.toLowerCase(),rows=b.directory.filter(t=>(!q||JSON.stringify([t.id,t.accountId,t.email,t.cohort,t.context]).toLowerCase().includes(q))&&(!f.elements.cohort.value||t.cohort===f.elements.cohort.value)&&(!f.elements.platform.value||t.context?.platform===f.elements.platform.value)&&(!f.elements.version.value||t.context?.appVersion===f.elements.version.value)&&(!f.elements.activity.value||(f.elements.activity.value==='ACTIVE')===(Date.parse(t.lastActive||'')>=Date.now()-7*86400000))&&(!f.elements.status.value||t.status===f.elements.status.value)&&(!f.elements.feedback.checked||t.feedbackCount>0)&&(!f.elements.errors.checked||t.errorCount>0));document.querySelector('#beta-directory').innerHTML=table(rows,[['Tester ID','id',id=>`<button data-beta-tester="${esc(id)}">${esc(id)}</button>`],...(operator?[['Email','email',esc]]:[]),['Status','status'],['Cohort','cohort'],['Invited','invitedAt',date],['Accepted','acceptedAt',date],['First observed install','firstInstall',date],['Last active','lastActive',date],['Platform / version','context',v=>esc([v?.platform,v?.appVersion,v?.buildNumber].filter(Boolean).join(' / '))],['Feedback','feedbackCount'],['Searches','searches'],['Errors','errorCount'],['Crash reports','crashes']]);document.querySelectorAll('[data-beta-tester]').forEach(button=>button.onclick=()=>{const t=b.directory.find(row=>row.id===button.dataset.betaTester);document.querySelector('#beta-tester-detail').innerHTML=panel('Tester detail · '+t.id,stats([['Status',t.status],['Cohort',t.cohort],['First observed install',date(t.firstInstall)],['Last active',date(t.lastActive)],['Searches',t.searches],['Feedback',t.feedbackCount],['Errors',t.errorCount],['Crashes',t.crashes]])+table(b.feedback.filter(f=>f.reporter===t.accountId),[['Bug','id'],['Status','status'],['Severity','severity'],['Title','title',esc]]))})};draw();document.querySelector('#beta-filter').onsubmit=e=>{e.preventDefault();draw()};
 document.querySelectorAll('[data-beta-action]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(f));if(f.dataset.betaAction==='target')body.value=Number(body.value);for(const key of ['enabled','passed','approved'])if(key in body)body[key]=body[key]==='true';try{await api('beta/'+f.dataset.betaAction,body);message('Recorded and audited.');render()}catch(error){message(error.message)}});
 document.querySelector('#beta-export')?.addEventListener('click',async()=>{try{const value=await api('beta/export',{format:'json'}),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='honorable-beta-aggregate.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){message(e.message)}});
 }catch(e){message(e.message)}
}
