(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.HonorableProject=factory()})(typeof globalThis!=='undefined'?globalThis:this,()=>{
'use strict';
const entitlement='HONORABLE_STUDIO_MONTHLY';
const capabilities={basicEdit:{status:'WORKING',entitlement:null},basicPoseRig:{status:'PARTIAL',entitlement:null,blocker:'Person segmentation and bounded image mesh deformation are not implemented.'},generativeFill:{status:'COMING_SOON'},expansion:{status:'COMING_SOON'},rigAnimation:{status:'COMING_SOON'},subjectSelection:{status:'COMING_SOON'},patch:{status:'COMING_SOON'},smartFilters:{status:'COMING_SOON'},raw:{status:'COMING_SOON'},relight:{status:'COMING_SOON'},smartLayers:{status:'COMING_SOON'},videoSequence:{status:'FOUNDATION'},cameraTracking:{status:'COMING_SOON'},video3d:{status:'COMING_SOON'},nodes:{status:'FOUNDATION'},geometry:{status:'COMING_SOON'},aiVideo:{status:'COMING_SOON'}};
for(const [key,value]of Object.entries(capabilities))if(!['basicEdit','basicPoseRig'].includes(key))value.entitlement=entitlement;
const clone=v=>JSON.parse(JSON.stringify(v));
const defaults=()=>({rotation:0,crop:1,brightness:1,contrast:1,saturation:1,exposure:0,filter:'none'});
function create(media){return{schemaVersion:1,name:media.name||'Untitled',media:[{id:'source',uri:media.uri,name:media.name||'Original',kind:media.type||'IMAGE',preserveOriginal:true}],activeLayerId:'original',layers:[{id:'original',type:media.type==='VIDEO'?'Video':'Image',name:'Original',mediaId:'source',visible:true,locked:false,opacity:1,transform:{x:0,y:0,rotation:0,scale:1},blendMode:'normal',mask:null}],adjustments:defaults(),timeline:{playhead:(media.timestamp||0)/1000,zoom:1,tracks:[],markers:[],keyframes:[]},nodes:{nodes:[],connections:[]},effects:[],files:{'scripts/main.py':{kind:'script',language:'python',text:'project.active_layer.opacity = 0.5\n'},'scripts/automation.java':{kind:'script',language:'java',text:'project.activeLayer().setOpacity(0.5);\n'},'assets':{kind:'folder'},'exports':{kind:'folder'}},macros:[],exports:[]}}
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v}
function serialize(p){return JSON.stringify(stable(p),null,2)}
function safePath(path){if(typeof path!=='string'||path.length>200||path.startsWith('/')||path.split('/').some(x=>!x||x==='.'||x==='..')||/[\\\u0000-\u001f]/.test(path)||['__proto__','constructor','prototype'].some(x=>path.split('/').includes(x)))throw Error('Invalid virtual project path');return path}
function fileOperation(p,op,from,to,text){p=clone(p);safePath(from);if(to)safePath(to);if(['create','folder'].includes(op)){if(p.files[from])throw Error('File already exists');p.files[from]=op==='folder'?{kind:'folder'}:{kind:'script',language:from.endsWith('.java')?'java':'python',text:text||''};}else{if(!p.files[from])throw Error('File not found');if(op==='save'){if(p.files[from].kind!=='script')throw Error('Not a script');p.files[from].text=text||''}else if(op==='delete'){for(const k of Object.keys(p.files))if(k===from||k.startsWith(from+'/'))delete p.files[k]}else if(['move','duplicate'].includes(op)){if(!to||to.startsWith(from+'/'))throw Error('Invalid destination');const keys=Object.keys(p.files).filter(k=>k===from||k.startsWith(from+'/'));for(const k of keys)if(p.files[to+k.slice(from.length)])throw Error('Destination exists');for(const k of keys){p.files[to+k.slice(from.length)]=clone(p.files[k]);if(op==='move')delete p.files[k]}}else throw Error('Unsupported file operation')}return p}
function timelineOperation(project,operation,{studio=false}={}){
 if(!studio)throw Error('STUDIO_REQUIRED');const p=clone(project),t=p.timeline;
 const track=t.tracks.find(x=>x.id===operation.trackId);
 if(operation.type==='addTrack'){if(t.tracks.some(x=>x.id===operation.id))throw Error('Duplicate track');t.tracks.push({id:operation.id,kind:operation.kind==='audio'?'audio':'video',clips:[]});}
 else if(operation.type==='addClip'){if(!track||!p.media.some(x=>x.id===operation.mediaId))throw Error('Missing track or media');if(!Number.isFinite(operation.duration)||operation.duration<=0)throw Error('Invalid duration');if(t.tracks.some(x=>x.clips.some(c=>c.id===operation.id)))throw Error('Duplicate clip');track.clips.push({id:operation.id,mediaId:operation.mediaId,start:0,in:0,out:operation.duration,speed:1,effects:[],layerIds:[],keyframes:[]});}
 else if(operation.type==='marker'){if(!Number.isFinite(operation.time)||operation.time<0)throw Error('Invalid marker');t.markers.push({time:operation.time,label:String(operation.label||'Marker').slice(0,100)});}
 else {const clip=track?.clips.find(c=>c.id===operation.clipId);if(!clip)throw Error('Missing clip');if(operation.type==='trim'){if(!Number.isFinite(operation.in)||!Number.isFinite(operation.out)||operation.in<0||operation.out<=operation.in||operation.out>clip.out)throw Error('Invalid trim');clip.in=operation.in;clip.out=operation.out;}
 else if(operation.type==='split'){const at=operation.time;if(!Number.isFinite(at)||at<=clip.in||at>=clip.out||t.tracks.some(x=>x.clips.some(c=>c.id===operation.id)))throw Error('Invalid split');const right={...clone(clip),id:operation.id,in:at,start:clip.start+(at-clip.in)/clip.speed};clip.out=at;track.clips.splice(track.clips.indexOf(clip)+1,0,right);}
 else if(operation.type==='move'){if(!Number.isFinite(operation.start)||operation.start<0)throw Error('Invalid clip start');clip.start=operation.start;track.clips.sort((a,b)=>a.start-b.start);}
 else throw Error('Unsupported timeline operation');}return p;
}
const permissions=['READ_PROJECT','WRITE_PROJECT','READ_PROJECT_MEDIA','CREATE_LAYERS','MODIFY_TIMELINE','USE_AI_OPERATION','RENDER_PROJECT'];
const scriptAPI={HonorableProject:['active_layer','layers','photo','video','timeline','subject','camera','render'],HonorableMedia:['inspect'],HonorableLayer:['opacity','transform'],HonorableTimeline:['add_clip'],HonorableClip:['trim'],HonorableSelection:['select'],HonorableTransform:['move','rotate','scale'],HonorableEffect:['parameters'],HonorableRig:['select_joint'],HonorableNodeGraph:['add_node','connect'],HonorableRender:['preview','export']};
const sandbox={python:'EDITOR_ONLY',java:'EDITOR_ONLY',validate(language,text){return{language,status:'EDITOR_ONLY',errors:typeof text!=='string'||text.length>100000?['Script exceeds editor limit']:[],message:'Execution is unavailable until a restricted runtime is integrated.'}},run(){throw Error('Sandbox runtime unavailable. No script was executed.')},stop(){return{running:false}}};
function route(capability,{studio=false,uploadConsent=false,requiresCloud=false}={}){const c=capabilities[capability];if(!c)throw Error('Unknown capability');if(c.entitlement&&!studio)return{allowed:false,reason:'STUDIO_REQUIRED'};if(c.status!=='WORKING')return{allowed:false,reason:c.status,blocker:c.blocker};if(requiresCloud&&!uploadConsent)return{allowed:false,reason:'UPLOAD_CONSENT_REQUIRED'};return{allowed:true}}
return{timelineOperation,create,defaults,serialize,fileOperation,capabilities,permissions,scriptAPI,sandbox,route,clone};
});
