import React from'react';
import{StyleSheet,Text}from'react-native';
import{createBottomTabNavigator}from'@react-navigation/bottom-tabs';
import{createNativeStackNavigator}from'@react-navigation/native-stack';
import{HomeScreen}from'../screens/HomeScreen';import{MemoriesScreen}from'../screens/MemoriesScreen';import{StorageScreen}from'../screens/StorageScreen';import{SettingsScreen}from'../screens/SettingsScreen';import{ModelsScreen}from'../screens/ModelsScreen';
import{PassScreen}from'../screens/PassScreen';
import{AboutLegalScreen,PrivacyPolicyScreen,TermsOfServiceScreen}from'../screens/LegalScreens';import{PlansScreen}from'../screens/PlansScreen';import{UsageScreen}from'../screens/UsageScreen';import{LockedFeatureScreen}from'../screens/LockedFeatureScreen';import{PrivacyDataScreen,SeranConsentScreen,SeranImprovementScreen}from'../screens/PrivacyDataScreen';
import{colors}from'../design-system';import type{MainTabParamList,RootStackParamList}from'./types';
import{selectionHaptic}from'../feedback/haptics';import{TabTransition}from'./TabTransition';
const Tabs=createBottomTabNavigator<MainTabParamList>();const Stack=createNativeStackNavigator<RootStackParamList>();
const symbols:Record<keyof MainTabParamList,string>={Home:'⌂',Memories:'▦',Pass:'◇',Models:'✦',Activity:'◫',Settings:'⚙'};
function TabIcon({name,color}:{name:keyof MainTabParamList;color:string}){return <Text style={[styles.icon,{color}]}>{symbols[name]}</Text>}
const HomeTab=()=> <TabTransition><HomeScreen/></TabTransition>;const MemoriesTab=()=> <TabTransition><MemoriesScreen/></TabTransition>;const PassTab=()=> <TabTransition><PassScreen/></TabTransition>;const ModelsTab=()=> <TabTransition><ModelsScreen/></TabTransition>;const ActivityTab=()=> <TabTransition><StorageScreen/></TabTransition>;const SettingsTab=()=> <TabTransition><SettingsScreen/></TabTransition>;
function MainTabs(){return <Tabs.Navigator screenListeners={({navigation,route})=>({tabPress:()=>{const state=navigation.getState();if(state.routes[state.index]?.key!==route.key)selectionHaptic()}})} screenOptions={({route})=>({headerShown:false,tabBarActiveTintColor:colors.ice,tabBarInactiveTintColor:colors.textMuted,tabBarStyle:styles.tabBar,tabBarLabelStyle:styles.label,tabBarIcon:({color})=><TabIcon color={color} name={route.name}/>})}><Tabs.Screen name="Home" component={HomeTab}/><Tabs.Screen name="Memories" component={MemoriesTab}/><Tabs.Screen name="Pass" component={PassTab}/><Tabs.Screen name="Models" component={ModelsTab}/><Tabs.Screen name="Activity" component={ActivityTab}/><Tabs.Screen name="Settings" component={SettingsTab}/></Tabs.Navigator>}
export function AppNavigator(){return <Stack.Navigator screenOptions={{headerShown:false,animation:'slide_from_right'}}><Stack.Screen name="MainTabs" component={MainTabs}/><Stack.Screen name="Plans" component={PlansScreen}/><Stack.Screen name="Usage" component={UsageScreen}/><Stack.Screen name="AboutLegal" component={AboutLegalScreen}/><Stack.Screen name="TermsOfService" component={TermsOfServiceScreen}/><Stack.Screen name="PrivacyPolicy" component={PrivacyPolicyScreen}/><Stack.Screen name="PrivacyData" component={PrivacyDataScreen}/><Stack.Screen name="SeranImprovement" component={SeranImprovementScreen}/><Stack.Screen name="SeranConsent" component={SeranConsentScreen}/><Stack.Screen name="LockedFeature" component={LockedFeatureScreen}/></Stack.Navigator>}
const styles=StyleSheet.create({icon:{fontSize:19},tabBar:{position:'absolute',left:18,right:18,bottom:12,height:62,borderRadius:31,backgroundColor:'rgba(12,16,22,.86)',borderTopWidth:1,borderTopColor:'rgba(255,255,255,.22)',paddingTop:5,shadowColor:'#000',shadowOffset:{width:0,height:16},shadowOpacity:.34,shadowRadius:26,elevation:14},label:{fontSize:10,fontWeight:'600'}});
